feat(nix): add nyx pro unlock
revanced/revanced-patches pull request #1004
Opened 2022-11-08 17:23 UTC by FineFindus

Unlocks the pro features of [Nyx Music Player](https://play.google.com/store/apps/details?id=com.awedea.nyx).

2022-11-08 19:02 UTC, oSumAtrIX requested changes
Looks good, apply the requested changes and we can get it merged.

2022-11-08 19:02 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/nyx/misc/pro/annotations/ProUnlockCompatibility.kt
> +        "com.awedea.nyx", arrayOf("2.2.5")
The constraint for the app version is probably unnecessary. Make sure to format the code again.
```suggestion
        "com.awedea.nyx"
```

2022-11-08 19:02 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/nyx/misc/pro/patch/ProUnlockPatch.kt
> +@Name("nyx-pro-unlock")
```suggestion
@Name("unlock-pro")
```

2022-11-08 19:02 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/nyx/misc/pro/patch/ProUnlockPatch.kt
> +class ProUnlockPatch : BytecodePatch(
Refactor all references from "ProUnlock" to "UnlockPro" (essentially swapping). It would be a bit more clear.

2022-11-08 19:22 UTC, oSumAtrIX requested changes

2022-11-08 19:22 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/nyx/misc/pro/fingerprints/UnlockProFingerprint.kt
> +@Name("unlock-pro")
Apply this name to the fingerprint as well. The names should somewhat convey what the fingerprint resolves to.
```suggestion
@Name("check-pro-fingerprint")
```

2022-11-08 19:22 UTC, FineFindus commented
I changed it.

2022-11-09 05:32 UTC, oSumAtrIX requested changes
Apply the requested change and lgtm

2022-11-09 05:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/nyx/misc/pro/fingerprints/UnlockProFingerprint.kt
> +object UnlockProFingerprint : MethodFingerprint(
Please name this `CheckProFingerprint` as the annotation.

2022-11-09 12:19 UTC, FineFindus commented
I hope this correct, I was a bit confused by the request.

2022-11-09 12:26 UTC, oSumAtrIX approved these changes

2022-11-09 12:46 UTC, merged

2022-11-09 12:47 UTC, oSumAtrIX commented
Thanks