feat: partial `sponsorblock` patch
revanced/revanced-patches pull request #101
Opened 2022-07-02 16:09 UTC by oSumAtrIX

2022-07-11 12:41 UTC, Sculas commented
Any updates on this patch?

2022-07-11 12:42 UTC, oSumAtrIX commented
It is being worked on.

2022-07-12 07:37 UTC, mchangrh requested changes
Additional requested changes
- handler for 403 responses
  This usually contains a warning for the user or a message explaining why the category is not accepting submissions.

- Force refresh before submitting if cache is enabled - This might mislead the user into thinking that a video doesn't have a segment and submitting a bad duplicate

misc:
if you need videos for testing, https://wiki.sponsor.ajay.app/w/Testing#Demo_Videos has a good selection (in interesting cases too)

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="segments_selfpromo_sum">Similar to "sponsor" except for unpaid or self promotion. This includes sections about merchandise, donations, or information about who they collaborated wit
```suggestion
    <string name="segments_selfpromo_sum">When there is unpaid or self promotion. This includes specific sections about merchandise, donations, or information about who they collaborated with</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="revanced_sb_firstrun">Are you aware of the SponsorBlock integration in Vanced? With it you can skip sponsored segments in the videos. You can enable/disable this in the settings at
```suggestion
    <string name="revanced_sb_firstrun">Are you aware of the SponsorBlock integration in ReVanced? With it you can skip sponsored segments in the videos. You can enable/disable this in the settings at any time.</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="segments_preview_sum">Quick recap of previous episodes, or a preview of what\'s coming up later in the current video. Meant for edited together clips, not for spoken summaries.</str
```suggestion
    <string name="segments_preview_sum">Recap of previous episodes, or a preview of what\'s coming up later in the current video or future videos in the same series. Intended for edited together clips that do not provide additional information.</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="sb_guidelines_preference_sum">Guidelines contain tips about submitting a segment</string>
```suggestion
    <string name="sb_guidelines_preference_sum">Guidelines contain tips and rules about submitting segments</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="segments_nomusic_sum">Only for use in music videos. This includes introductions or outros in music videos</string>
```suggestion
    <string name="segments_nomusic_sum">Only for use in music videos. This includes any content not in the Spotify Release</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="segments_subscribe_sum">When there is a short reminder to like, subscribe or follow them in the middle of content</string>
```suggestion
    <string name="segments_subscribe_sum">When there is a short reminder to like, subscribe, follow or interact with them on any paid or free platform</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="sb_guidelines_popup_content">It\'s recommended to read the Sponsor Block guidelines before submitting any segment</string>
```suggestion
    <string name="sb_guidelines_popup_content">It\'s recommended to read the SponsorBlock guidelines before submitting any segment</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="general_browser_button_sum">Clicking this button under the player will open sb.ltn.fi where you can see more details about segments.</string>
```suggestion
    <string name="general_browser_button_sum">Clicking this button under the player will open sb.ltn.fi where you can see all the segments on the video.</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="segments_filler_sum">Tangential scenes added only for filler or humor that are not required to understand the main content of the video. This should not include segments providing c
```suggestion
    <string name="segments_filler_sum">Tangential scenes added only for filler or humor that are not required to understand the main content of the video. This should not include context or background details</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="segments_endcards_sum">Credits or when the YouTube endcards appear. Not spoken conclusions</string>
```suggestion
    <string name="segments_endcards_sum">Credits or when the YouTube endcards appear. Not for spoken conclusions</string>
```

2022-07-12 07:37 UTC, mchangrh commented on src/main/resources/sponsorblock/values/strings.xml
> +    <string name="general_min_duration_sum">Segments shorter than the set value (in seconds) will not be skipped or show in the player</string>
```suggestion
    <string name="general_min_duration_sum">Segments shorter than the set value (in seconds) will not be skipped or shown in the player</string>
```

2022-07-12 08:23 UTC, mchangrh commented
Sorry about that, I thought that GH allowed accepting all changes in one commit. I'll make a PR in future.

2022-07-12 08:25 UTC, oSumAtrIX commented
> Sorry about that, I thought that GH allowed accepting all changes in one commit. I'll make a PR in future.

2022-07-17 23:17 UTC, merged