feat(twitch/integrations): Add integrations support for Twitch
revanced/revanced-patches pull request #1074
Opened 2022-11-19 13:17 UTC by ThePBone

Waiting for #1052, so I can add the new integrations patch abstraction.

Depends on: https://github.com/revanced/revanced-integrations/pull/216

2022-11-21 21:17 UTC, ThePBone commented
I rebased #1052 onto this PR and updated it to support the abstract integrations patch. Should be ready to go now.

2022-11-21 21:31 UTC, oSumAtrIX commented
Seems like rebasing caused issues since the other PR you rebased on was squashed before merge. Can you revert the rebase/rebase onto main?

2022-11-21 21:42 UTC, ThePBone commented
I had to force-push to overwrite the old commits; it is up-to-date now.

2022-11-21 21:43 UTC, oSumAtrIX approved these changes

2022-11-21 21:56 UTC, oSumAtrIX requested changes

2022-11-21 21:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitch/misc/integrations/patch/TwitchIntegrationsPatch.kt
> +@Name("twitch-integrations")
The application name can be omitted here because patches are already scoped to packages implicitely.

```suggestion
@Name("integrations")
```

2022-11-21 21:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitch/misc/integrations/patch/TwitchIntegrationsPatch.kt
> +class TwitchIntegrationsPatch : AbstractIntegrationsPatch(
For the same reason as the other suggestion, this class should be named Integrations, as there is no reason to name the app due to the class being already in the correct package for twitch patches. Reflect this change with the compatibility annotation class as well.

2022-11-23 06:27 UTC, oSumAtrIX approved these changes

2022-11-23 06:30 UTC, merged