refactor(tiktok): patch name convention.
revanced/revanced-patches pull request #1085
Opened 2022-11-22 02:46 UTC by d4rkk3y

2022-11-22 07:09 UTC, oSumAtrIX requested changes
Looks good, i've left some suggestions from me on the naming. Before merge the changes should also be reflected to the class names, such as omitting "Tiktok", because the patch is already in the correct package.

2022-11-22 07:09 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/ad/patch/TiktokAdsPatch.kt
> +@Name("ads")
```suggestion
@Name("hide-ads")
```

2022-11-22 07:09 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/misc/forcelogin/patch/DisableForceLoginPatch.kt
> +@Name("mandatory-login")
```suggestion
@Name("disable-login-requirement")
```

2022-11-22 07:09 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/misc/loginfallback/patch/TikTokLoginFallbackPatch.kt
> +@Name("web-login")
```suggestion
@Name("fix-google-login")
```

2022-11-28 01:38 UTC, oSumAtrIX approved these changes
Did you also consider the integrations & package names?

2022-11-28 02:07 UTC, d4rkk3y commented
> Did you also consider the integrations & package names?

What should I change in integrations?

2022-11-28 02:11 UTC, oSumAtrIX commented
No i was just wondering, if there were any changes required for the integrations as well, checked and it seems fine.

2022-11-28 02:11 UTC, merged