fix: Use correct `description`, `title` & `summary` for `URL-redirect` patch
revanced/revanced-patches pull request #1488
Opened 2023-01-14 17:13 UTC by johnconner122

2023-01-14 17:20 UTC, Ushie commented
Doesn't this change make the purpose of the setting more confusing?

2023-01-14 17:38 UTC, johnconner122 commented
> What's the purpose of this PR?

This patch was designed to bypass youtube.com/redirect, but changed its description to open links in browser while refactoring.

2023-01-14 17:47 UTC, Ushie commented
Does this change help the user understand the function of this patch better?

2023-01-14 17:58 UTC, johnconner122 commented
I guess, yes.

2023-01-14 18:59 UTC, oSumAtrIX requested changes
Couple inconsistencies, these descriptions are used interchangeably:

- Redirect
- Redirects
- youtube.com/redirect

Additionally, the tense changes. Sometimes the descriptions are in present sometimes in future tense.

Please chose either in favour of consistency.

2023-01-15 02:56 UTC, oSumAtrIX requested changes

2023-01-15 02:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/misc/openlinksdirectly/patch/OpenLinksDirectlyPatch.kt
> +                StringResource("revanced_uri_redirect_summary_off", "Links will follow default redirect policy")
```suggestion
                StringResource("revanced_uri_redirect_summary_on", "Bypassing URL redirects"),
                StringResource("revanced_uri_redirect_summary_off", "Following default redirect policy")
```

2023-01-15 02:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/misc/openlinksdirectly/patch/OpenLinksDirectlyPatch.kt
> +                StringResource("revanced_uri_redirect_title", "Bypass URL redirect"),
```suggestion
                StringResource("revanced_uri_redirect_title", "Bypass URL redirects"),
```

2023-01-15 02:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/misc/openlinksdirectly/patch/OpenLinksDirectlyPatch.kt
> +@Description("Bypasses URL redirects inside YouTube app.")
```suggestion
@Description("Bypasses https://youtube.com/redirect URLs.")
```

2023-01-15 02:56 UTC, oSumAtrIX approved these changes

2023-01-15 02:57 UTC, merged