feat(Instagram): Add fix integrations patch
revanced/revanced-patches pull request #1695
Opened 2023-03-02 21:37 UTC by falafelp

should fix https://github.com/revanced/revanced-patches/pull/1672#issuecomment-1444265925
and makes it possible to develop patches that use integrations for instagram

2023-03-02 21:38 UTC, Ushie commented
This PR isn't necessary, it's incorrect to do this as the issue lies within the Patcher/Frontends (such as CLI/Manager), not in the patches.

2023-03-02 21:38 UTC, Ushie commented
The issue is already resolved in Dev branches of the responsible repositories, only the ReVanced Manager remains.

2023-03-02 22:05 UTC, oSumAtrIX commented
Well, merging shouldn't cause an issue to begin with, this PR would be useful in the case integrations are required in the future

2023-03-03 23:59 UTC, oSumAtrIX commented
How does it work/ Why does it fail in the first place when integrations are merged?

2023-03-12 21:24 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/integrations/patch/FixIntegrationsPatch.kt
> +@Version("0.0.1")
This patch should only be used as a dependency for other patches which depend on possibly future integrations
```suggestion
@Description("Prevents crashing when new classes are added.")
@Version("0.0.1")
```

2023-03-12 21:25 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/integrations/patch/FixIntegrationsPatch.kt
> +            val field = ((result!!.method.implementation!!.instructions.elementAt(startIndex+2) as Instruction21c).reference as DexBackedFieldReference)
You can use result.mutableMethod.instruction() here. Please reduce duplicates here.

2023-03-12 21:25 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/integrations/patch/FixIntegrationsPatch.kt
> +            val classname = field.definingClass
Please give the variables a proper explanatory name. It is unclear what they are.

2023-03-12 21:26 UTC, oSumAtrIX requested changes
Please check on the review

2023-03-15 13:54 UTC, closed without merging