chore(songpal): Attempt to make patches more resilient
revanced/revanced-patches pull request #2386
Opened 2023-06-10 19:52 UTC by 1fexd

As already discussed in #2369, I have attempted to make the patches more resilient.

2023-06-10 20:47 UTC, oSumAtrIX commented
Made some changes, please check if everything works as expected

2023-06-10 21:57 UTC, 1fexd commented
Looks good. I have also pushed an update to the method name.

2023-06-10 22:21 UTC, oSumAtrIX requested changes

2023-06-10 22:21 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/songpal/badge/fingerprints/ShowNotificationFingerprint.kt
> +        "f", // While the method is called "f" in 9.5.0, this may change in a future version, so it is not used for matching.
I don't think "f" is useful, just give the method reference an explaining name such as `showNotification` and comment the version of the app this fingerprint was made for somewhere

2023-06-11 09:07 UTC, 1fexd commented
Is this better?

2023-06-11 13:21 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/songpal/badge/fingerprints/ShowNotificationFingerprint.kt
> +        "getOrCreateBadge", // This is the non-obfuscated method name, but this is not used for matching since it may change due to R8/Proguard
```suggestion
        "getOrCreateBadge", // Non-obfuscated placeholder method name
```

2023-06-11 13:53 UTC, merged