feat(Tiktok-Playback speed): remember playback speed
ReVanced/revanced-patches pull request #2506
Opened 2023-12-17 12:10 UTC by d4rkk3y

integration changes: https://github.com/ReVanced/revanced-integrations/pull/543
close: https://github.com/ReVanced/revanced-patches/issues/433

2023-12-17 19:35 UTC, oSumAtrIX requested changes

2023-12-17 19:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/fingerprints/ChangeSpeedFingerprint.kt
> +internal object ChangeSpeedFingerprint : MethodFingerprint(
Are all attributes necessary for the fingerprint? If there is no particular reason, you may remove some attributes.

2023-12-17 19:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +object PlaybackSpeedPatch : BytecodePatch(
This patch currently does two things at a same time. You may want to separate it, but its not necessary

2023-12-17 19:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                        " Lapp/revanced/tiktok/speed/SpeedPatch;->saveDefaultSpeed(F)V"
You may call this method "rememberPlaybackSpeed"

2023-12-17 19:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
>      override fun execute(context: BytecodeContext) {
This patch has 3 blocks of code. Please add // region comments to document what each block of code does/ what its purpose is

2023-12-17 19:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                const/4 v0, 0x1
It is unknown what the registers are or what these instructions do. Please document it with comments (# Comment)

2023-12-17 21:22 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +object PlaybackSpeedPatch : BytecodePatch(
I think it is OK because these things support each other.

2023-12-21 14:12 UTC, oSumAtrIX requested changes

2023-12-21 14:12 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                const/4 v0, 0x1
What is this constant? Why does it have to be 1?

2023-12-21 14:12 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                # Second argument is a Aweme. It is some kind of data for a TikTok video.
What is Aweme and what data is it? Why is it necessary to call `changeSpeedMethod`?

2023-12-21 16:53 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                const/4 v0, 0x1
It is actually a boolean value. And I did not find out what it was. I set it to "true" because most of the time I see it set to "true" in decompiled code.

2023-12-21 17:10 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                # Second argument is a Aweme. It is some kind of data for a TikTok video.
Aweme is a object which store data for a TikTok video. Here is some method of its class: 
https://github.com/ReVanced/revanced-integrations/blob/main/dummy/src/main/java/com/ss/android/ugc/aweme/feed/model/Aweme.java

2023-12-21 17:11 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                # Second argument is a Aweme. It is some kind of data for a TikTok video.
I have just found a simpler approach without using that. I am testing it.

2023-12-21 18:13 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                # Second argument is a Aweme. It is some kind of data for a TikTok video.
> I have just found a simpler approach without using that. I am testing it.

Nvm, it is not work.

2023-12-21 18:16 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                # Second argument is a Aweme. It is some kind of data for a TikTok video.
Why is the object necessary to change the object?

2023-12-22 16:58 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/speed/PlaybackSpeedPatch.kt
> +                # Second argument is a Aweme. It is some kind of data for a TikTok video.
> Why is the object necessary to change the speed?

Afaik, when the handle play speed changed event, app will call Aweme.getAid() from that object to get the video identifier and compare it with the getCurrentAweme().getAid(). If they are different,  app will set the speed to 1.0f.
![image](https://github.com/ReVanced/revanced-patches/assets/43563783/f62e7a89-ef13-460f-a4be-5cab331fb0a2)

2024-01-02 16:36 UTC, oSumAtrIX commented
I have pushed some changes. Please check if it looks good and if the names for the fingerprints I inferred from the code is correct.

2024-01-03 13:03 UTC, d4rkk3y commented
> I have pushed some changes. Please check if it looks good and if the names for the fingerprints I inferred from the code is correct.

I tested it, and it worked well. But I think the fingerprint's name should not be `OnVideoSwiped` because it literally resolve to the method used to change video speed.

2024-01-09 19:10 UTC, merged

2024-01-10 07:54 UTC, oSumAtrIX commented
Integrations aren't merged yet