feat(Tiktok-ClearMode): Retains the clear mode configurations
ReVanced/revanced-patches pull request #2509
Opened 2023-12-17 16:17 UTC by d4rkk3y

integration changes: https://github.com/ReVanced/revanced-integrations/pull/544
close: https://github.com/ReVanced/revanced-patches/issues/2507

2023-12-17 19:43 UTC, oSumAtrIX requested changes

2023-12-17 19:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/fingerprints/OnRenderFirstFrameFingerprint.kt
> +    customFingerprint = { methodDef, _ ->
Since this fingerprint is present in another PR but both prs are unrelated they are in their respective patch package, after either is merged, please remember to move it to a shared location.

2023-12-17 19:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +    description = "Retains the clear mode configurations in between videos.",
Is "Clear mode" a known term in TikTok? If not you should use known terminology and avoid inventing words.

2023-12-17 19:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +        CompatiblePackage("com.ss.android.ugc.trill", ["32.5.3"]),
Is the constraint necessary?

2023-12-17 19:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +                            "Lapp/revanced/tiktok/clearmode/ClearModePatch;->saveClearModeState(Z)V"
You can rename this method to "rememberClearModeState"

2023-12-17 19:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +                    new-instance v0, $clearModeEventClass
It is unknown what these instructions do, please add inline comments (# comment) and document magic constants and abstract lines of instructions (or their purpose) to make it easy to understand what the patch is doing

2023-12-17 19:46 UTC, oSumAtrIX requested changes

2023-12-17 19:46 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +object ClearModePatch : BytecodePatch(
Name this patch according to what it achieves. In this case a better name would be RememberClearModePatch. Rename the integrations class, the patch name accordingly and use "remember" instead of "retain" as it is a simpler term

2023-12-17 22:44 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +    description = "Retains the clear mode configurations in between videos.",
Yes, they did use it but in code like package name, class name...So is it OK to keep file name ClearModePatch.kt and change patch name to `Clear display`?

2023-12-17 22:56 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/ClearModePatch.kt
> +        CompatiblePackage("com.ss.android.ugc.trill", ["32.5.3"]),
I think yes. Because TikTok is frequently updated and I am not sure this will work in next versions. In addition, if someone want to patch the newer version, they could disable version compatibility check.

2023-12-18 00:06 UTC, d4rkk3y commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/RememberClearModePatch.kt
> +                    # Third is a Boolean which is the state of clear mode.
I agree. I will change it.

2023-12-19 17:51 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tiktok/interaction/clearmode/RememberClearModePatch.kt
> +    name = "Clear display",
Is the feature called clear display or clear mode in TikTok? Please use the one that is used in TikTok and rename classes accordingly

2023-12-21 14:16 UTC, oSumAtrIX reviewed
A quick Google search revealed that this feature is known as Clear mode. I am not sure why this patch is called "Clear display".

2023-12-21 14:22 UTC, oSumAtrIX approved these changes

2023-12-21 14:24 UTC, merged

2023-12-21 14:25 UTC, oSumAtrIX commented
Seems like TikTok renamed the setting to "Clear display" 🤦