feat(YouTube): Clarify and simplify patch descriptions
ReVanced/revanced-patches pull request #2519
Opened 2023-12-19 05:17 UTC by KobeW50

This PR appends `Adds option to...` to all patches that can be toggled or customized within the patched app. It also aims to simplify the descriptions to make them easier to understand for non-technical users.

2023-12-19 05:52 UTC, KobeW50 commented
I have a few thoughts and questions before I move forward with simplifying the descriptions.

1. The `Disable precise seeking gesture` should be renamed to `Disable precise seeking`. I don't see how saying anything about the "gesture" is useful.
2.  For GmsCore, the description says `Allows Google apps to run without root and...` but I think it should say that it allows __patched__ Google apps to un without root.
3. Do album cards only appear in search results? If yes, I'll specify that in the patch description.
4. For `Hide email address`, does it hide multiple email addresses if there are multiple accounts? I couldn't test bec the patch wasn't working. 
5. For RYD, should I clarify that it "...shows the __estimated__ dislike count"?

2023-12-19 06:46 UTC, oSumAtrIX commented
5. Use the description that RYD officially provides

2023-12-19 17:03 UTC, KobeW50 commented
@LisoUseInAIKyrios Do you know about 3 and 4?

2023-12-19 22:50 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/misc/dimensions/spoof/SpoofDeviceDimensionsPatch.kt
> +    description = "Adds option to spoof the device dimensions in order to unlock higher video qualities that may not be available on your device.",
I combined this into a single string. Not sure if this is correct.

2023-12-20 04:52 UTC, KobeW50 reviewed
Some thoughts and notes on the changes:

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +    description = "Adds option to disable precise seeking when swiping up on the seekbar.",
Note: I didn't change the patch name (to `Disable precise seeking`) because I would then need to change the file name and all references to the "precise seeking gesture" in the file and in the integrations which is beyond the scope of this PR.

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/EnableSlideToSeekPatch.kt
> +    description = "Adds option to enable slide to seek instead of playing at 2x speed when pressing and holding in the video player.",
I was thinking that it might be incorrect that in the `Seekbar tapping` patch we use the term "tap-to-seek" but here we don't add hyphens to "slide to seek" (although YouTube doesn't use hyphens). Should probably just keep it like this.

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/action/HideButtonsPatch.kt
> +    description = "Adds options to hide action buttons (such as the Download button) under videos.",
This example may be oversimplified or overly specific, although a similar style example is given for the `Disable player popup panels` patch, which currently says "Disables panels (such as live chat) from opening automatically."

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/navigation/NavigationButtonsPatch.kt
> +    description = "Adds options to hide and change navigation buttons (such as the Shorts button).",
This example may be oversimplified or overly specific, although a similar style example is given for the `Disable player popup panels` patch, which currently says "Disables panels (such as live chat) from opening automatically."

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/infocards/HideInfoCardsPatch.kt
> +    description = "Adds option to hide info cards that creators add in the video player.",
This wording can work, but my gut tells me there is a better possible wording.

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/time/HideTimestampPatch.kt
> +    description = "Adds option to hide the timestamp in the bottom left of the video player.",
This may be oversimplified, but I think the meaning of "timestamp" isn't completely obvious and this doesn't make the description lengthy.

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/startpage/ChangeStartPagePatch.kt
> +    description = "Adds option to set which page the app opens in instead of the homepage.",
This wording can work, but my gut tells me there is a better possible wording.

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/tabletminiplayer/TabletMiniPlayerPatch.kt
> +    description = "Adds option to enable the tablet mini player layout.",
I can't think of a more descriptive explanation even though most people don't understand what the tablet mini player layout is or looks like.

2023-12-20 04:52 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/misc/dimensions/spoof/SpoofDeviceDimensionsPatch.kt
> +    description = "Adds option to spoof the device dimensions which unlocks higher video qualities if they aren't available on the device.",
Note: I combined this into one string. Not sure if that's an issue.

2023-12-20 06:43 UTC, ILoveOpenSourceApplications commented
I also noticed some patch descriptions having "options". One example is the `hide general ads` patch, which is understandable as the patch provides multiple options to disable different types of ads. Is this followed throughout for other patches having "options " in its description? (Just for confirmation)

2023-12-20 06:43 UTC, ILoveOpenSourceApplications requested changes

2023-12-20 06:43 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/youtube/interaction/copyvideourl/CopyVideoUrlBytecodePatch.kt
It's odd to have two "add" in a single sentence. Instead it can be "Adds option to include buttons in the video player for copying video links." Also the patch name and description is having two terms, "URL" and "links" respectively.  Should be changed to any one for consistency and depending on what YouTube likes to call it.

2023-12-20 06:47 UTC, KobeW50 commented
> Is this followed throughout for other patches having "options " in its description? (Just for confirmation)

Yes. Ony patches that add multiple toggles say "options"

2023-12-20 14:31 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/interaction/copyvideourl/CopyVideoUrlBytecodePatch.kt
> It's odd to have two "add" in a single sentence. Instead, it can be "Adds option to include buttons in the video player for copying video links." 

 I think the double use of "add" is fine. Also none of the synonyms such as "include", "insert", or "place" describe it better than "add".

@oSumAtrIX do you have any thoughts on this? It is regarding the proposed description for `Copy video url` which is `Adds options to add buttons in the video player to copy video links.`

https://github.com/ReVanced/revanced-patches/pull/2519/files/d7421f2e728f7e2939bc916eba51dede81b4050d#diff-22338d330003b349bc6cf36a81663cc334707165ab988005171d5e096a1a2ddeR12

> Also the patch name and description is having two terms, "URL" and "links" respectively. Should be changed to any one for consistency and depending on what YouTube likes to call it.

Good point. Also "url" in the patch name needs to be capitalized.

2023-12-20 14:34 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/copyvideourl/CopyVideoUrlBytecodePatch.kt
"Adds options to display buttons..."

2023-12-20 14:39 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/ad/video/VideoAdsPatch.kt
> +    description = "Adds option to remove ads in the video player.",
In all places that say "Adds option to..."?

2023-12-20 14:49 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/ad/video/VideoAdsPatch.kt
> +    description = "Adds option to remove ads in the video player.",
What is your question

2023-12-20 15:01 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/ad/video/VideoAdsPatch.kt
> +    description = "Adds option to remove ads in the video player.",
You said this is a mistake in the example above, and I assume you mean it is a grammatical error, which means that in the dozens of descriptions that start with `Adds option to...` I should correct it by changing them to `Adds the option to...`. Is this correct?

Or is this "mistake" a less general grammatical error that doesn't necessarily apply to all instances of `Adds option to...`?

2023-12-20 15:19 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/ad/video/VideoAdsPatch.kt
> +    description = "Adds option to remove ads in the video player.",
If the patch only adds a single toggle its "Adds an option" if it adds more its "Adds options"

2023-12-25 05:36 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/misc/dimensions/spoof/SpoofDeviceDimensionsPatch.kt
> +    description = "Adds option to spoof the device dimensions which unlocks higher video qualities if they aren't available on the device.",
Can the explanation be on a new line, similar to the side effects of the signature spoof toggles?

![photostudio_1703482544452.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/48394b53-6e4d-412d-8dbb-abfa4495946c)

A pop-up isn't as appropriate like the spoof-app-version pop-up because in the case of spoofing the version, the pop-up is also giving a warning and instructions if an issue occurs. Here it is just a short description

2023-12-27 04:44 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +                StringResource("revanced_disable_precise_seeking_gesture_title", "Disable precise seeking"),
This change would need to be propagated to the key as well as variables, names in the patch and integrations as well. Basically everywhere where "gesture" was used previously.

2023-12-27 04:45 UTC, oSumAtrIX approved these changes
lgtm, please rebase and consider newly included patch descriptions as well

2023-12-27 04:54 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +                StringResource("revanced_disable_precise_seeking_gesture_title", "Disable precise seeking"),
Makes sense. I'm too lazy to get into the weeds of all that, so I'll just revert this change for now.

2023-12-27 23:39 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +                StringResource("revanced_disable_precise_seeking_gesture_title", "Disable precise seeking"),
I reverted the changes to the in-app settings for this patch. The patch description still has this change

![image](https://github.com/ReVanced/revanced-patches/assets/84587632/d679eebe-2a78-4bfb-951b-a7e887572dce)

2023-12-28 00:09 UTC, KobeW50 commented
> lgtm, please rebase and consider newly included patch descriptions as well

Done (I hope I didn't screw anything up)

2024-01-01 15:30 UTC, merged

2024-01-01 19:03 UTC, KobeW50 commented
@oSumAtrIX thank you for merging this pr. Please link the related issues so that they are closed when this is merged with 'main'.

https://github.com/ReVanced/revanced-patches/issues/2515

https://github.com/ReVanced/revanced-patches/issues/740

https://github.com/ReVanced/revanced-patches/issues/1054