(Change header): Change patch name and improve descriptions
ReVanced/revanced-patches pull request #2581
Opened 2024-01-03 02:17 UTC by KobeW50

Closes https://github.com/ReVanced/revanced-patches/issues/2580

2024-01-03 02:21 UTC, oSumAtrIX requested changes

2024-01-03 02:21 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +            Can be a header name or a path to a custom header folder to use in the top bar.
"Header name" is kinda difficult to understand

```suggestion
            Either a header name or a path to a custom header folder to use in the top bar.
```

2024-01-03 02:21 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +            A path to a folder must contain one or more of the following folders matching the DPI of your device:
We refer to the specific path if used for the option.
```suggestion
            The path to a folder must contain one or more of the following folders matching the DPI of your device:
```

2024-01-03 02:21 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +    name = "Custom header",
Patches named by their action is better. "Change header" says what this patch does. Revert the changes regarding the patch name

2024-01-03 02:43 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +    name = "Custom header",
Many patches don't follow this rule. This patch is very similar to `Custom branding` which is a reason to give them consistent names. Also, "custom" tells the user what they can do with the patch while "change" is ambiguous.

2024-01-03 02:44 UTC, KobeW50 commented
If the patch name would change, in lines 95 and 102 of CustomHeaderPatch.kt there is a bit of code that is still named change-header

I didn't change this to custom-header because I wasn't sure what it does.

https://github.com/ReVanced/revanced-patches/commit/b596b2c37b8a2766bc35dbf5d30675fa07f68656#diff-5e83a02d14cb9cd781c7acbde6850469bc0fb34b637cb6a8fd0d1fa798819b6dL95-R102

2024-01-03 02:51 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +    name = "Custom header",
Like I said, it contributes to the problem, just because other patches contribute to it, doesn't excuse this patch to too.

2024-01-03 02:52 UTC, oSumAtrIX commented
Keep the patch name as is, don't change it to custom header. You'd also need to commit the API changes besides

2024-01-03 03:29 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +            Can be a header name or a path to a custom header folder to use in the top bar.
> "Header name" is kinda difficult to understand

Perhaps all patch option presets should be referred to as a "preset" or synonymous term

2024-01-03 10:01 UTC, Pamilg8 commented
![Screenshot_20240103-135842](https://github.com/ReVanced/revanced-patches/assets/149590337/02fa764e-3245-4b81-aa6a-bee1a4ec5959)
A patch to change that too. Pls

2024-01-06 03:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +            Can be a header name or a path to a custom header folder to use in the top bar.
This terminology would be introduced here and nowhere else which would be inconsistent. If you want this to change, do so please in a separate PR consistently

2024-01-06 23:19 UTC, KobeW50 commented on src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/CustomHeaderPatch.kt
> +            Can be a header name or a path to a custom header folder to use in the top bar.
It's fine for now. Maybe in the future if it's needed.

I don't have a better term than "header name" so I believe this PR is ready to be merged.

2024-01-09 19:06 UTC, oSumAtrIX approved these changes

2024-01-09 19:07 UTC, merged