feat(OpeningHours): fix crash
ReVanced/revanced-patches pull request #2697
Opened 2024-02-07 03:42 UTC by Linus789

Old PR: https://github.com/ReVanced/revanced-patches-template/pull/3271

As LisoUseInAIKyrios suggested I contacted the developer of the app. He said that it was a hobby project and there won't be any updates. I asked if he could make the source code public, but I haven't received a reply and several months have already passed.

And thanks oSumAtrIX for letting me know of the new repository. As you suggested I have re-opened the PR here.

2024-02-08 19:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/crash/fingerprints/SetPlaceFingerprint.kt
> +object SetPlaceFingerprint : MethodFingerprint(
```suggestion
internal object SetPlaceFingerprint : MethodFingerprint(
```

2024-02-08 19:17 UTC, oSumAtrIX requested changes
There's a lot going on in this patch. Please explain why this many changes are needed.

2024-02-08 19:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +                continueLabel1,
Please add comments on whats this doing

2024-02-08 19:17 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +            )
Please add comments on whats this doing

2024-02-08 20:36 UTC, Linus789 commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +            )
Done :)

2024-02-08 20:37 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +            // Again, we only added null checks and jump to label continue_0 if they return true.
Can't you use replaceInstruction? Why do the original instructions crash?

2024-02-08 20:53 UTC, Linus789 commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +            // Again, we only added null checks and jump to label continue_0 if they return true.
The original instructions crash because they look like this
```
invoke-virtual {p1}, Lde/simon/openinghours/models/Place;->getOpeningHours()Lde/simon/openinghours/models/OpeningHours;
move-result-object v0
invoke-static {v0}, Lkotlin/jvm/internal/Intrinsics;->checkNotNull(Ljava/lang/Object;)V
invoke-virtual {v0}, Lde/simon/openinghours/models/OpeningHours;->getWeekdayText()Lio/realm/RealmList;
move-result-object v0
invoke-static {v0}, Lkotlin/jvm/internal/Intrinsics;->checkNotNull(Ljava/lang/Object;)V
check-cast v0, Ljava/util/List;
invoke-direct {p0, v0}, Lde/simon/openinghours/views/custom/PlaceCard;->setWeekDayText(Ljava/util/List;)V
```

Yes, it should be possible to replace `Intrinsics;->checkNotNull` with the `if-eqz` check. I don't remember why I didn't do that in the first place. It seems like the only way adding new labels to a method is using `addInstructionsWithLabels`, though.

2024-02-08 20:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +            // Again, we only added null checks and jump to label continue_0 if they return true.
You can create labels manually. Check how `addInstructionsWithLabels` is implemented. Also document things like this in the code

2024-02-08 22:18 UTC, Linus789 commented on src/main/kotlin/app/revanced/patches/openinghours/crash/CrashPatch.kt
> +            // Again, we only added null checks and jump to label continue_0 if they return true.
Better like this?

2024-02-23 01:19 UTC, oSumAtrIX requested changes

2024-02-23 01:19 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/misc/fix/crash/FixCrashPatch.kt
> +            avoidNullPointerException(getOpeningHoursIndex[1], setWeekDayTextIndex, 0)
The registers could change in future versions. Regardless of the version this patch is pinned to, it is better practice to get the register dynamically in case we want to remove the pin.

2024-02-23 01:19 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/openinghours/misc/fix/crash/FixCrashPatch.kt
> +            fun avoidNullPointerException(openingHoursIndex: Int, jumpOverIndex: Int, targetRegister: Int) {
Please give the parameters more concrete names. Currently, they are very generic, requiring you to infer what they are.

I have inferred the current names.

2024-02-24 17:14 UTC, Linus789 commented on src/main/kotlin/app/revanced/patches/openinghours/misc/fix/crash/FixCrashPatch.kt
> +            avoidNullPointerException(getOpeningHoursIndex[1], setWeekDayTextIndex, 0)
Thanks for the refactor. :+1: I have now added the dynamic register use.

2024-02-26 03:49 UTC, oSumAtrIX approved these changes

2024-02-26 03:50 UTC, merged