feat(Twitter/X): Use chooser when opening links
ReVanced/revanced-patches pull request #2730
Opened 2024-02-14 15:51 UTC by dic1911

As title, let me know if I missed anything.

2024-02-14 15:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitter/misc/browserchooser/BrowserChooserPatch.kt
> +        result.mutableMethod.removeInstructions(0, instructions.count())
Simply injecting at index 0 should suffice

2024-02-14 15:56 UTC, oSumAtrIX requested changes
Looks good all in all. I'll push some small changes, until then you can look into the current review

2024-02-15 05:59 UTC, dic1911 commented on src/main/kotlin/app/revanced/patches/twitter/misc/browserchooser/BrowserChooserPatch.kt
> +            addInstructions(
Agreed, here's the PR for that.
https://github.com/ReVanced/revanced-integrations/pull/570

2024-02-15 06:01 UTC, dic1911 commented on src/main/kotlin/app/revanced/patches/twitter/misc/browserchooser/BrowserChooserPatch.kt
> +        result.mutableMethod.removeInstructions(0, instructions.count())
Just force pushed with things cleaned up, tested on my side and seems to be working good.

2024-02-16 19:09 UTC, oSumAtrIX requested changes
Pushed some changes, please test them. (You have to include the patch as `use = false`).
In the integrations I have also removed instantiating a new intent and instead overwrote the action. Is that even necessary?

2024-02-17 04:22 UTC, dic1911 commented
@oSumAtrIX the `--include`/`-i` flag doesn't work on my side, I can't test it with `use` set to false.

2024-02-21 03:21 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitter/misc/links/OpenLinksWithAppChooserPatch.kt
> +    override fun execute(context: BytecodeContext) {
```suggestion

    override fun execute(context: BytecodeContext) {
```

2024-02-21 03:22 UTC, merged