feat(Mi Fitness): MiBand CN language fix + app login to mi servers
ReVanced/revanced-patches pull request #2734
Opened 2024-02-15 16:43 UTC by pisek

Added patches for MiFitness to get Mi Band CN version to use english language without changing the phone locale to EN

2024-02-16 20:15 UTC, oSumAtrIX requested changes

2024-02-16 20:15 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/locale/ForceLocalePatch.kt
> +            val instructionIndex = scanResult.patternScanResult!!.startIndex
Please name this instruction index to something more specific. What code is the index pointing to semantically?

2024-02-16 20:15 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +    description = "Fixes login for uncertified Mi Fitness app",
What exactly does this fix? The login to the wearables app?

2024-02-16 20:15 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/fingerprints/LoginFingerprint.kt
> +internal object LoginFingerprint : MethodFingerprint(
Please name this fingerprint according to the method it resolves to.

2024-02-16 20:15 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
Are you sure parameter 2 is never gonna change?

2024-02-16 20:15 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/locale/ForceLocalePatch.kt
> +    description = "Forces the locale to a specific language",
Is this patch changing the language of the wearables app or wearables connecting to it?

2024-02-18 11:10 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/locale/ForceLocalePatch.kt
> +    description = "Forces the locale to a specific language",
Wearables connecting to it. Example: Mi Band 8 CN version, reads locale of the phone. If it is ENG, wearable also sets language to ENG. But if phone locale is anything else then ENG, then Mi Band defaults lantuage to Chinese. Therefore, this patch mocks locale of the phone to ENG so, no matter what locale is the phone set to, it will set Mi Band to ENG

2024-02-18 11:12 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/locale/ForceEnglishLocalePatch.kt
> +    description = "Forces the app to use the English locale.",
Forcing the wearable only. No change in language of the app itself.

2024-02-19 08:37 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/locale/ForceLocalePatch.kt
> +            val instructionIndex = scanResult.patternScanResult!!.startIndex
It is a move-result-object where we put a resolved phone locale to the register.
I have renamed it accordingly.

2024-02-19 08:50 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/fingerprints/LoginFingerprint.kt
> +internal object LoginFingerprint : MethodFingerprint(
ok

2024-02-19 08:51 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
Well, no i am not sure as i am not the owner of the original app;)
Any proposal of how to do it in a better way?

2024-02-20 03:31 UTC, oSumAtrIX requested changes

2024-02-20 03:31 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
If this parameter is used somewhere in the code, you can obtain it from one of the instructions. If the compiled code updates the register count, the parameter 2 shifts accordingly, but since you'd obtain it from an existing instruction, you'd correctly reference the necessary register.

2024-02-26 15:58 UTC, pisek commented
Could anyone of you guy take a look at what is wrong with the build?
`Error: Input required and not supplied: gpg_private_key`
I am not sure what to do with it...

2024-02-26 16:22 UTC, oSumAtrIX commented
The GPG key is necessary for the publication tasks; this is not relevant in the build task:

<img width="321" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/3b68069d-2432-4fa9-8bfc-94e96c2bd6f3">

2024-02-29 11:18 UTC, pisek commented
Ok, so as I understand, it is ready to be merged :)

2024-03-02 07:12 UTC, oSumAtrIX requested changes

2024-03-02 07:12 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
@pisek The parameter seems still to be hardcoded

2024-03-19 12:47 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
What do you mean?
I have changed XiaomiAccountManagerConstructorFingerprint to point directly to the param that i need.

2024-03-19 13:03 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
In this case, the fingerprint could fail to resolve, which is about as fatal as the parameter changing because the patch would stop working in both cases. Instead, if you obtain the register from an existing instruction, the failure would be reduced down to the instruction shifting changing or moving. For now this is fine.

2024-03-20 11:36 UTC, pisek commented on src/main/kotlin/app/revanced/patches/mifitness/misc/login/FixLoginPatch.kt
> +            "const/4 p2, 0x0",
Ok, i have updated the code to get the reg from instruction. Could you re-review?

2024-03-25 20:53 UTC, merged