fix(redditisfun): Change User-Agent to generic Android browser UA
ReVanced/revanced-patches pull request #2743
Opened 2023-08-03 17:57 UTC by nandryshak

As mentioned in my comment in #2727, I believe that changing the user agent to something that clearly identifies the app as being modified by revanced presents a security risk:

1) It risks the user of the app being banned by reddit for ToS violations.

2) It risks revanced getting a cease & desist from reddit. This is because the new way of generating a "more convincing" UA no longer has any plausible deniability. Before, the random number did not distinctly identify the app as being modded by revanced. Now, it does.

3) It makes it super easy for reddit to ban these user agents again in the future.

The first solution that came to my mind is to user a generic browser user agent together with the random number. 

Let me know your thoughts on this, and let me know if I'm missing any conventions or PR etiquette for this particular project.

2023-08-03 19:46 UTC, oSumAtrIX requested changes
No detective work is present, as explained in #2727 and the user agent proposed in this PR violates the one Reddit expects:

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/87cee34a-8d85-4f31-9017-836c0701e660)

Use a schema that follows this format.

2023-08-03 20:01 UTC, nandryshak commented
> No detective work is present, as explained in #2727 and the user agent proposed in this PR violates the one Reddit expects:
> 
> ![image](https://user-images.githubusercontent.com/13122796/258220007-87cee34a-8d85-4f31-9017-836c0701e660.png)
> 
> Use a schema that follows this format.

That's useful to know, thanks. In this case I wonder if it's worth it to allow each user to add their own UA in the same way that we add our client id token.

2023-08-03 20:05 UTC, dgw commented
> In this case I wonder if it's worth it to allow each user to add their own UA in the same way that we add our client id token.

I'd say it is worthwhile. According to the prescribed format, whoever owns the application (generated the client ID) should be the `/u/name` that's included in the UA string, as I interpret the guidelines.

2023-08-03 20:06 UTC, oSumAtrIX commented
You could add an option but the default one should be randomized

2023-08-03 20:35 UTC, Forceu commented
I would suggest that each user has to provide an agent string, similar to how the API ID has to be provided by the user. That way it is ensured that a unique ID is used, has the username and this project would not violate the t&c

2023-08-03 22:23 UTC, DaviddH commented
It seems broken again now as i just mentioned in my original issue, why not mirror the UA of the official reddit app to prevent it from being blocked?

2023-08-03 22:31 UTC, nandryshak commented
> It seems broken again now as i just mentioned in my original issue, why not mirror the UA of the official reddit app to prevent it from being blocked?

Mine is still working okay. 

As mentioned by oSumAtrIX above and by someone else in 2727, spoofing the official app's UA would be a ToS violation, and they "will ban liars with extreme prejudice". 

So it definitely seems like we need the ability to use a custom UA. I can work on adding that tomorrow.

2023-08-19 13:55 UTC, oSumAtrIX commented
Is this still being worked on?

2023-08-21 13:28 UTC, nandryshak commented
> Is this still being worked on?

Yes, but I haven't put time into it recently. I'll see if I can get to it this week.

2023-09-03 17:45 UTC, oSumAtrIX commented
Reopen once ready.

2023-09-03 17:45 UTC, closed without merging