feat(YouTube): Hide `Suggetions shelf`
ReVanced/revanced-patches pull request #2951
Opened 2024-03-29 16:44 UTC by johnconner122

closes: #469, #494

2024-03-29 16:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/suggestionsshelf/HideSuggestionsShelfPatch.kt
> +    name = "Hide Suggestions shelf",
```suggestion
    name = "Hide suggestions shelf",
```

2024-03-29 16:50 UTC, oSumAtrIX commented
Please run the apiDump Gradle task:

https://github.com/ReVanced/revanced-patches/actions/runs/8483332498/job/23244311783?pr=2951

2024-03-29 16:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/suggestionsshelf/HideSuggestionsShelfPatch.kt
> +    description = "Hides suggestions shelf on the homepage tab.",
I forgot to submit my review, this is what I wanted to add as well, the description should clarify what suggestions shelf is. Also it should say "Adds an option to" which was recently added to all patches that add an option to do that.

2024-03-29 17:23 UTC, johnconner122 commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/suggestionsshelf/HideSuggestionsShelfPatch.kt
> +    description = "Hides suggestions shelf on the homepage tab.",
Should I add summary to patch description or preference summary?

2024-04-04 14:19 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/suggestionsshelf/HideSuggestionsShelfPatch.kt
> +    description = "Adds an option to hide suggestions shelf on the homepage tab.",
```suggestion
    description = "Adds an option to hide suggestions shelves (e.g. Breaking news) on the homepage tab.",
```

2024-04-04 14:19 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="revanced_hide_suggestions_shelf_title">Hide Suggestions shelf</string>
```suggestion
            <string name="revanced_hide_suggestions_shelf_title">Hide suggestions shelf</string>
```

2024-04-04 14:20 UTC, oSumAtrIX requested changes
Since there are multiple types of shelves, maybe the term "shelf" should be changed to "shelves", but not sure.

2024-04-05 06:01 UTC, ILoveOpenSourceApplications commented
Since the term "suggestions" is used which itself implies multiple, I think shelf is enough.

2024-04-05 13:49 UTC, oSumAtrIX commented
@ILoveOpenSourceApplications suggestions shelf means a single shelf doing suggestions, whereas suggestions shelves means, multiple kinds of shelves doing suggestions which is the case here

2024-04-05 22:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/breakingnews/BreakingNewsPatch.kt
This class should be deprecated to not break API.

2024-04-05 22:44 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="revanced_hide_suggestions_shelf_summary_on">Shelves are hidden, which includes:\n• Breaking news\n• Continue watching\n• Explore more channels\n• Shopping\n• Watch it Again<
```suggestion
            <string name="revanced_hide_suggestions_shelf_summary_on">Shelves are hidden such as:\n• Breaking news\n• Continue watching\n• Explore more channels\n• Shopping\n• Watch it Again</string>
```

2024-04-05 22:45 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="revanced_hide_suggestions_shelf_title">Hide suggestions shelf</string>
String and preference keys as well as names should either use "Suggestions shelves" or "Suggestions shelf". In some places such as the description of the setting it says "Shelves" and in other places "Shelf".

2024-04-06 01:30 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="revanced_hide_suggestions_shelf_title">Hide suggestions shelf</string>
What I meant was, similar to how we say "Hide ads" instead of "Hide ad" we would also need to say "Hide shelves" as there's multiple types of shelves in addition to multiple shelves, not just one such as a cast button.

2024-04-06 18:40 UTC, oSumAtrIX approved these changes

2024-04-06 18:42 UTC, oSumAtrIX commented
Looks like I have not tested the latest commit I pushed, because it failed to install without me noticing, I'll check quickly

2024-04-06 18:49 UTC, merged