feat(tumblr): add fix api updates patch
ReVanced/revanced-patches pull request #2954
Opened 2024-03-30 16:02 UTC by leumasme

Recent changes in the tumblr API have made all old versions of the app break due to removal of Tumblr Live.
Many API requests fail with the error `Unknown attribute 'live_now' requested`.
API paths are defined via annotations. This patch stops old app versions from requesting the removed fields by patching the function to handle these annotations to remove occourances of `,?live_now`

2024-03-30 22:48 UTC, oSumAtrIX requested changes

2024-03-30 22:48 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +    description = "Fixes old versions of the app to break due to Tumblr removing remnants of Tumblr Live from the API, " +
Which version is last that worked? You can add that to the description to say "Prior version x".

2024-03-30 22:48 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +                # p2 is "value" string which has the value of the annotation (= the request path)
Please explain what "value" string means. Is it the request URL?

2024-03-30 23:14 UTC, leumasme commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +                # p2 is "value" string which has the value of the annotation (= the request path)
It's the request path, as the comment says. "value" is the name of the parameter. The original source code of the function is also linked in a comment at the fingerprint definition
https://github.com/square/retrofit/blob/ebf87b10997e2136af4d335276fa950221852c64/retrofit/src/main/java/retrofit2/RequestFactory.java#L270-L302

2024-03-30 23:16 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +                # p2 is "value" string which has the value of the annotation (= the request path)
What 
```suggestion
                # Remove "?live_now" from the request path p2.
```

2024-03-30 23:42 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +    use = false,
@leumasme The patch is disabled by default as its unsuitable for new versions, sounds good?

2024-03-31 00:44 UTC, leumasme commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +    description = "Fixes old versions of the app to break due to Tumblr removing remnants of Tumblr Live from the API, " +
Some painful binary search later, 33.3 is the first version that works; <=33.2 are broken. The current grammar of the description is also completely broken so i changed it, feel free to reword again.

2024-03-31 00:45 UTC, leumasme commented on src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt
> +    use = false,
Yeah that's fine.

2024-03-31 00:46 UTC, oSumAtrIX approved these changes

2024-03-31 00:46 UTC, merged