fix(YouTube - GmsCore support): Prompt to disable battery optimizations, if not done already
ReVanced/revanced-patches pull request #2958
Opened 2024-03-31 09:57 UTC by LisoUseInAIKyrios

If GmsCore is not whitelisted from device power optimizations:
- Show a dialog explaining why they need to turn off power optimizations
- Open the prompt to turn off optimizations

This is much simpler than opening a website explaining more changes.

If GmsCore is not running in the background on app launch, then the dontkillmyapp.com is still opened, as that condition needs instructions specific to the users device and operating system (a simple exclude from battery optimizations likely will not fix it).

[Integration changes](https://github.com/ReVanced/revanced-integrations/pull/601)

<details>

![dialog](https://github.com/ReVanced/revanced-patches/assets/118716522/27400dd7-1073-43fd-98ee-f9c8f9b48da4)

![permission](https://github.com/ReVanced/revanced-patches/assets/118716522/d60c5956-65ee-4a38-8588-feefe95b3e96)

</details>

2024-03-31 12:59 UTC, oSumAtrIX commented
GmsCore is the new official name of MicroG. I don't think it makes sense to mislabel it. If at all, I'd call it MicroG GmsCore.

2024-04-02 01:22 UTC, oSumAtrIX requested changes

2024-04-02 01:22 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="gms_core_dialog_not_whitelisted_not_allowed_in_background_message">MicroG GmsCore does not have permission to run in the background.\n\nFollow the \"Don\'t kill my app\" gui
```suggestion
            <string name="gms_core_dialog_not_whitelisted_not_allowed_in_background_message">MicroG GmsCore does not have permission to run in the background.\n\nFollow the \"Don\'t kill my app\" guide for your phone, and apply the instructions to your MicroG installation.\n\nThis is required for the app to work.</string>
```

2024-04-02 01:22 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="gms_core_dialog_not_whitelisted_using_battery_optimizations_message">MicroG GmsCore battery optimizations must be turned off to prevent app crashes.\n\nPress the continue bu
Turned off -> Disabled (Probably a simpler term)
App crashes -> Issues (Crashes arent the only issue, playback could also silently fail apparently)
```suggestion
            <string name="gms_core_dialog_not_whitelisted_using_battery_optimizations_message">MicroG GmsCore battery optimizations must be disabled to prevent issues.\n\nPress the continue button and disable battery optimizations.</string>
```

2024-04-02 01:22 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="gms_core_toast_user_did_not_whitelist_message">Battery optimizations are still on, and this app may not work</string>
```suggestion
            <string name="gms_core_toast_not_whitelisted_message">MicroG GmsCore requires disabling battery optimizations</string>
            <!-- Translations of this should not be longer than what is here, otherwise the text can be clipped and not entirely shown. -->
            <string name="gms_core_toast_user_did_not_whitelist_message">Battery optimizations are still enabled and can cause issues</string>
```

2024-04-04 14:30 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/music/misc/gms/GmsCoreSupportPatch.kt
> -    mainActivityOnCreateFingerprint = ApplicationInitFingerprint,
If

2024-04-04 14:31 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/music/misc/gms/fingerprints/MusicActivityOnCreateFingerprint.kt
> +internal object MusicActivityOnCreateFingerprint : MethodFingerprint(
Since `ApplicationInitFingerprint` (for integrations currently) has been replaced with `MusicActivityOnCreateFingerprint`, perhaps `MusicActivityOnCreateFingerprint` can be used for integrations as well instead of `ApplicationInitFingerprint`? If so, the fingerprint can be moved to a shared location.

2024-04-04 14:31 UTC, oSumAtrIX approved these changes

2024-04-04 14:32 UTC, oSumAtrIX commented on src/main/resources/addresources/values/strings.xml
> +            <string name="gms_core_dialog_not_whitelisted_using_battery_optimizations_message">MicroG GmsCore battery optimizations must be disabled to prevent issues.\n\nPress the continue button an
```suggestion
            <string name="gms_core_dialog_not_whitelisted_using_battery_optimizations_message">MicroG GmsCore battery optimizations must be disabled to prevent issues.\n\nTap on the continue button and disable battery optimizations.</string>
```

2024-04-06 18:46 UTC, merged

2024-04-22 00:06 UTC, d-e-n-n-i-s-t commented
Why does this have to keep annoying users that don't need to whitelist MicroG GmsCore? I don't use background playback/notifications, so why do I have to dismiss this annoying popup everytime I open ReVanced YouTube? Atleast create an option to disable this popup.

2024-04-22 00:13 UTC, oSumAtrIX commented
GmsCore must run in the background for the app to work correctly, not just for notifications.

2024-04-22 00:26 UTC, d-e-n-n-i-s-t commented
Not true from my experience, I never had any issues with it's Battery Optimization Setting being on restricted (worse than default, "optimized"). Weirdly, even background playback works for me up to an hour (haven't used it longer yet)

2024-04-22 00:30 UTC, oSumAtrIX commented
If it runs anyways in the background you have no reason to worry about setting it to unrestricted. Once you can provide evidence on setting the option to unrestricted being problematic we can reconsider.

2024-04-22 00:37 UTC, d-e-n-n-i-s-t commented
Yeah, Im not doing that for anyone to "reconsider". It's a matter of principle; only apps that absolutely need it, should be set to unrestricted - it doesn't need to run in idle sleep.
I guess this is where it stays then, just want to annotate that its really inconsiderate to not create a toggle for that popup. Seems to me like it goes against the general pathos of ReVanced, as you can turn off any annoying popups, except this one.

2024-04-22 01:17 UTC, oSumAtrIX commented
> Yeah, Im not doing that 

Feel free to open an issue once you change your mind, as it stands, no change is necessary.