build/bump-dependencies
ReVanced/revanced-patches pull request #2974
Opened 2023-09-10 17:21 UTC by Axelen123

2023-09-10 18:51 UTC, validcube requested changes
Blargh

2023-09-10 18:51 UTC, validcube commented on src/main/kotlin/app/revanced/patches/backdrops/misc/pro/ProUnlockPatch.kt
>  import app.revanced.patches.backdrops.misc.pro.annotations.ProUnlockCompatibility
Not needed

2023-09-10 18:51 UTC, validcube commented on src/main/kotlin/app/revanced/patches/backdrops/misc/pro/ProUnlockPatch.kt
>  @ProUnlockCompatibility
Use new format

```kt
@Patch(
  compatiblePackages = [
    CompatiblePackage(
      "<package name>",
      arrayOf[<versions>]
     )
  ]
)
```

2023-09-11 16:23 UTC, oSumAtrIX commented
Please fix merge conflicts after moving patches to the correct directory. Examples:

/patch/some.kt -> /some.kt
/bytecode/fingerprints/ -> /fingerprints
/resource/some.kt -> /some.kt
...

2023-09-12 23:09 UTC, oSumAtrIX commented
Superseded by #2946

2023-09-12 23:09 UTC, closed without merging