ci: Separate Crowdin pull and push actions
ReVanced/revanced-patches pull request #2979
Opened 2024-04-01 23:11 UTC by Ushie

2024-04-01 23:18 UTC, oSumAtrIX requested changes

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/pull_strings.yml
> +name: Pull strings from Crowdin
```suggestion
name: Pull strings
```

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/push_strings.yml
> +name: Push strings to Crowdin
```suggestion
name: Push strings
```

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/push_strings.yml
> +        runs-on: ubuntu-latest
```suggestion
    push:
        name: Push strings
        runs-on: ubuntu-latest
```

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/pull_strings.yml
> +        runs-on: ubuntu-latest
```suggestion
    pull:
        name: Pull strings
        runs-on: ubuntu-latest
```

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/push_strings.yml
> +            - name: Push strings to Crowdin
```suggestion
            - name: Push strings
```

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/push_strings.yml
> +                  download_translations: false
```suggestion
```

2024-04-01 23:18 UTC, oSumAtrIX commented on .github/workflows/pull_strings.yml
> +                  upload_translations: false
```suggestion
```

2024-04-01 23:25 UTC, oSumAtrIX requested changes

2024-04-01 23:25 UTC, oSumAtrIX commented on .github/workflows/pull_strings.yml
> +            - name: Pull strings from Crowdin
```suggestion
            - name: Pull strings
```

2024-04-01 23:34 UTC, merged

2024-04-02 12:57 UTC, Ushie commented on .github/workflows/pull_strings.yml
> +        - cron: 0 * 1 * *
Oops, no, it's not 🤦‍♂️

@oSumAtrIX 4 eyes again