refactor: Migrate patches to DSL
ReVanced/revanced-patches pull request #3107
Opened 2024-05-02 01:58 UTC by Ushie

2024-05-02 02:01 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/cast/HideCastButtonPatch.kt
> +        )
Unsure if this is the intended way to do this

2024-05-02 02:02 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/navigation/NavigationButtonsPatch.kt
> +            val stringIndex = it.scanResult.stringsScanResult!!.matches.find { match ->
Unresolved reference: scanResult

2024-05-02 02:04 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/player/hide/HidePlayerButtonsPatch.kt
> +}
Is this where this should be moved?

2024-05-02 19:06 UTC, oSumAtrIX requested changes

2024-05-02 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +        isSwipingUpResult.let {
let not needed

2024-05-02 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/EnableSeekbarTappingPatch.kt
> +        val seekbarTappingMethods = onTouchEventHandlerResult.let {
let not needed. Needs to be fixed in multiple places

2024-05-02 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/autocaptions/AutoCaptionsPatch.kt
>          ).forEach { (fingerprint, enabled) ->
fingerprint ->result

2024-05-02 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/action/HideButtonsPatch.kt
> +    description = "Hides action buttons (such as the Download button) under videos.",
Description was changed

2024-05-02 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/buttons/action/HideButtonsPatch.kt
> +        addResources("youtube", "layout.buttons.action.hideButtonsPatch")
The patchId is incorrect. Keep it the same name as it was before. Its usually the package + patch class name. This has to be fixed in multiple places

2024-05-02 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/hide/albumcards/fingerprints/AlbumCardsFingerprint.kt
> +internal val albumCardsFingerprint = literalValueFingerprint({ albumCardId }) {
Name the parameter: literalSupplier = ...

2024-05-03 17:31 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/twitch/ad/embedded/EmbeddedAdsPatch.kt
> +    dependsOn(VideoAdsPatch, integrationsPatch, SettingsPatch, addResourcesPatch)
I left these for you to do as they were a bit complicated

2024-05-03 17:46 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/ShowDeletedMessagesPatch.kt
> +    dependsOn(integrationsPatch, SettingsPatch, addResourcesPatch)
I left these for you to do as they were a bit complicated, SettingsPatch for Twitch has not yet been migrated

2024-05-03 18:05 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/youtube/interaction/downloads/DownloadsPatch.kt
> +//        mainActivityResult.mutableMethod.implementation?.instructions.lastIndex = ""
Need help here

2024-05-03 18:13 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +        isSwipingUpResult.let {
How else would I do this? `addMovementIndex` is used twice

2024-05-03 18:15 UTC, Ushie commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/EnableSeekbarTappingPatch.kt
> +        val seekbarTappingMethods = onTouchEventHandlerResult.let {
How else would I do this?

2024-06-01 01:56 UTC, oSumAtrIX requested changes

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/finanzonline/detection/bootloader/fingerprints/BootStateFingerprint.kt
> +    accessFlags(AccessFlags.PUBLIC.value)
.value isnt necessary

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/idaustria/detection/root/fingerprints/AttestationSupportedCheckFingerprint.kt
> +    custom{ methodDef, _ ->
here the second argument "classDef" can be used so that below classDef.endsWith can be used

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/memegenerator/misc/pro/fingerprints/IsFreeVersionFingerprint.kt
> +    strings("free")
should probably order properly and move this below opcodes

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/photomath/detection/deviceid/SpoofDeviceIdPatch.kt
>          """
Please format the code. Multiline strings can get unformatted when you shift them

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/serviceportalbund/detection/root/RootDetectionPatch.kt
> +    compatibleWith("at.gv.bka.serviceportal"())
() is not necessary anymore and can be removed. Instead passing a string works now.

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/spotify/navbar/PremiumNavbarTabResourcePatch.kt
> +internal var showBottomNavigationItemsTextId = -1L
The setter should be made private on such properties.

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/twitch/chat/autoclaim/AutoClaimChannelPointsPatch.kt
> +        addResources(this)
Unfortunately, since we dont use classes anymore the two arg overload should be used for now. in this case: addResources("twitch", "chat.autoclaim.AutoClaimChannelPointsPatch").
The old class name should be used.

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/DisablePreciseSeekingGesturePatch.kt
> +        isSwipingUpResult.let {
I corrected it

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/EnableSeekbarTappingPatch.kt
> +        val seekbarTappingMethods = onTouchEventHandlerResult.let {
corrected here as well.

2024-06-01 01:56 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/EnableSlideToSeekPatch.kt
> +    val integrationsClassDescriptor = "Lapp/revanced/integrations/youtube/patches/SlideToSeekPatch;"
It was decided to move this to a private (or if necessary internal) constant above the patch, because sometimes fingerprints reference it to keep it consistent.

2024-06-10 13:59 UTC, merged