feat(Google News): Add Google News Patches, CustomTabs and GMSCore Integration
ReVanced/revanced-patches pull request #3111
Opened 2024-05-02 19:09 UTC by benjy3gg

This Patch implements CustomTabs in Google News (com.google.android.apps.magazines).
This sets a flag that is otherwise false to true -> Instead of opening articles in ChromeWebView it uses the Default Browser

This also implements Basic GMSCore Support.
Login and Logout works.
Clicking on "Manager your Google Account" doesn't open the GMSCore settings -> same problem as in Youtube.

2024-05-02 19:20 UTC, benjy3gg commented
depends on this pullrequest in revanced-integrations:
https://github.com/ReVanced/revanced-integrations/pull/628

otherwise i get an error in the onCreate method of StartActivity

2024-05-02 20:02 UTC, oSumAtrIX requested changes

2024-05-02 20:02 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/fingerprints/StartActivityInitFingerprint.kt
> +    },
The resolver lambdas are quite complex. It would be preferable to simplify them

2024-05-02 20:02 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportPatch.kt
> +            // google news
Thats not specific to google news, move it to // misc

2024-05-03 16:52 UTC, benjy3gg commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/fingerprints/StartActivityInitFingerprint.kt
> +    },
okay, could you help me make it simple?

2024-05-03 16:53 UTC, benjy3gg commented on src/main/kotlin/app/revanced/patches/magazines/misc/gms/ClientSpoofPatch.kt
> +    description = "Spoofs the client to allow video playback.",
removed it

2024-05-04 18:30 UTC, benjy3gg commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/fingerprints/StartActivityInitFingerprint.kt
> +    },
tried my best with my limited kotlin knowledge 😅

2024-05-25 22:46 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/customtabs/UseCustomTabs.kt
> +package app.revanced.patches.magazines.misc.customtabs
It's probably better to move the package from magazines to "googlenews". I was thinking about moving everything under the respective app's package, so for YouTube, the patches would be in: `app.revanced.patches.com.google.android.youtube`. For now, naming it "googlenews" is conventional with how we named the other packages.

2024-05-25 22:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/customtabs/fingerprints/UseCustomTabsFingerprint.kt
> +        methodDef.definingClass == "Lcom/google/apps/dots/android/modules/reading/customtabs/CustomTabsArticleLauncher;" && methodDef.accessFlags == AccessFlags.PUBLIC or AccessFlags.CONSTRUCTOR
Probably an .endsWith() check is simpler here.

2024-05-25 22:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/customtabs/fingerprints/UseCustomTabsFingerprint.kt
> +        methodDef.definingClass == "Lcom/google/apps/dots/android/modules/reading/customtabs/CustomTabsArticleLauncher;" && methodDef.accessFlags == AccessFlags.PUBLIC or AccessFlags.CONSTRUCTOR
AccessFlags is a field in MethodFingerprint. Use that.

2024-05-25 22:48 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/misc/gms/fingerprints/GooglePlayUtilityFingerprint.kt
> +internal object GooglePlayUtilityFingerprint : MethodFingerprint(
This fingerprint looks similar to another. Might remove one and move the other to a shared location under app.revanced.patches package similar to other shared fingerprints. The fingerprint can then be used in both patches.

2024-05-25 22:55 UTC, oSumAtrIX requested changes

2024-05-25 22:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/fingerprints/StartActivityInitFingerprint.kt
> +        instructions = method.toMutable().getInstructions()
A toMutabe call should not be necessary. You can simply get the methods instructions via method.implementation.instructions

2024-05-25 22:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/fingerprints/StartActivityInitFingerprint.kt
> +private var instructions: List<Instruction> = listOf()
This field is not necessary. contextRegisterResolver has a reference to the method.

2024-05-25 22:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/fingerprints/StartActivityInitFingerprint.kt
> +private var index: Int = -1
Move this field into the fingerprint object.

2024-06-02 15:51 UTC, oSumAtrIX commented
@benjy3gg Is this PR still active?

2024-06-07 22:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/magazines/misc/integrations/IntegrationsPatch.kt
> +        StartActivityInitFingerprint
Are there any other exported activities that can be launched? Because if so, they should be added here because if they are launched, context would not be hooked.

2024-06-14 18:20 UTC, Araxeus commented
any news on this?

2024-06-19 23:44 UTC, xob0t commented
i wanted to test it, but the patched app crashes on startup

logcat

```
06-20 02:37:48.967  7287  7287 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4489)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4456)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4430)] [androidx.transition.Transition$Impl26$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:53)] [com.google.apps.dots.android.modules.system.NSConnectivityManager.<init>(PG:116)] [com.google.apps.dots.android.modules.system.NSConnectivityManager_Factory.get(PG:27)] [dagger.internal.DoubleCheck.get(PG:16)] [com.google.apps.dots.android.newsstand.DaggerNSApplication_HiltComponents_SingletonC$SingletonCImpl.getConnectivityManager(PG:3)] [com.google.apps.dots.android.newsstand.NSDepend.setUp(PG:2772)] [com.google.apps.dots.android.newsstand.provider.NSContentProvider.onCreate(PG:12)] [android.content.ContentProvider.attachInfo(ContentProvider.java:2516)] [android.content.ContentProvider.attachInfo(ContentProvider.java:2486)] [android.app.ActivityThread.installProvider(ActivityThread.java:8308)] [android.app.ActivityThread.installContentProviders(ActivityThread.java:7810)] [android.app.ActivityThread.handleBindApplication(ActivityThread.java:7564)] [android.app.ActivityThread.access$1700(ActivityThread.java:315)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)]
06-20 02:37:49.008  7287  7287 W droid.magazine: Rejecting class com.google.apps.dots.android.app.activity.CurrentsStartActivity that attempts to sub-type erroneous class com.google.apps.dots.android.newsstand.activity.StartActivity in /data/app/~~vEfoNxz89LoeFAD-bWMpRg==/app.revanced.android.magazines-jUfXiRLr-6NeCZl1TZ1kkw==/base.apk!classes4.dex
06-20 02:37:49.008  7287  7287 E AndroidRuntime: java.lang.VerifyError: Rejecting class com.google.apps.dots.android.app.activity.CurrentsStartActivity that attempts to sub-type erroneous class com.google.apps.dots.android.newsstand.activity.StartActivity (declaration of 'com.google.apps.dots.android.app.activity.CurrentsStartActivity' appears in /data/app/~~vEfoNxz89LoeFAD-bWMpRg==/app.revanced.android.magazines-jUfXiRLr-6NeCZl1TZ1kkw==/base.apk!classes4.dex)
06-20 02:37:49.008  7287  7287 E AndroidRuntime: Caused by: java.lang.VerifyError: Verifier rejected class com.google.apps.dots.android.newsstand.activity.StartActivity: void com.google.apps.dots.android.newsstand.activity.StartActivity.onCreate(android.os.Bundle) failed to verify: void com.google.apps.dots.android.newsstand.activity.StartActivity.onCreate(android.os.Bundle): [0x1C] register v3 has type Undefined but expected Reference: android.content.Context (declaration of 'com.google.apps.dots.android.newsstand.activity.StartActivity' appears in /data/app/~~vEfoNxz89LoeFAD-bWMpRg==/app.revanced.android.magazines-jUfXiRLr-6NeCZl1TZ1kkw==/base.apk!classes4.dex)
```
google news apk v.5.108.0.63841370
revanced-integrations v1.10.0
revanced-cli v4.6.0

2024-07-05 09:03 UTC, xob0t commented
The GmsCore patch crashes the app.
Tested with Google news v5.108.0.638413701, revanced-cli-4.6.0-all.jar and revanced-integrations-1.11.0.apk
Frida crash log
```
Process crashed: java.lang.VerifyError: Verifier rejected class com.google.apps.dots.android.newsstand.activity.StartActivity: void com.google.apps.dots.android.newsstand.activity.StartActivity.onCreate(android.os.Bundle) failed to verify: void com.google.apps.dots.android.newsstand.activity.StartActivity.onCreate(android.os.Bundle): [0x1C] register v3 has type Undefined but expected Reference: android.content.Context (declaration of 'com.google.apps.dots.android.newsstand.activity.StartActivity' appears in base.apk!classes4.dex)
```
changing register to v2 in this line of the decompiled patched app fixes the crash
```smali
invoke-static/range {v3 .. v3}, Lapp/revanced/integrations/shared/Utils;->setContext(Landroid/content/Context;)V
```

2024-07-20 02:46 UTC, oSumAtrIX commented
The latest releases of Google News use Android SDK 35. https://github.com/iBotPeaches/Apktool/commit/25826db41770d1cd5b8f35a80b132fb4c5441637 needs to be updated for resource patches to work. Pinning the GmsCore support patch to `"5.108.0.644447823".

2024-07-20 02:53 UTC, oSumAtrIX approved these changes

2024-07-20 02:55 UTC, merged