GH-3099: Pin Reddit to 2024.0.17 until GH-3099 is addressed
ReVanced/revanced-patches pull request #3156
Opened 2024-05-12 12:08 UTC by ascopes

Until GH-3099 is fixable and addressed, this limits the version of Reddit that can be
used to 2024.0.17 which is the last known working version.

2024-05-12 12:13 UTC, ascopes commented
Not part of this MR but possibly worth noting that the link to the docs explaining how to structure the commit naming seems to be broken, so the name of this commit is a bit of a stab in the dark on my behalf.

Hopefully this is correct.

2024-05-12 23:41 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/reddit/ad/banner/HideBannerPatch.kt
> +    // Pinned to 2024.0.17 until https://github.com/iBotPeaches/Apktool/issues/3534
```suggestion
    // Constrained to last working version (2024.0.17) until https://github.com/iBotPeaches/Apktool/issues/3534
```

2024-05-12 23:43 UTC, oSumAtrIX requested changes
Since this patch is a dependency and not usable in any frontend, it inherits the compatibility of the dependant patches. For that reason, the compatibility needs to be set on the patches which depend on this one. Alternatively, this patch can get a name & other patches can stop depend on it so that they can be used on later versions with this patch unselected.

2024-05-13 05:18 UTC, ascopes commented
If I go for the latter, is it just a case of setting the name attribute directly or do other patches need modifying as well?

Apologise if it is a silly question, somewhat new to how this works!

2024-05-13 08:03 UTC, programminghoch10 requested changes

2024-05-13 08:03 UTC, programminghoch10 commented on src/main/kotlin/app/revanced/patches/reddit/ad/banner/HideBannerPatch.kt
> +    compatiblePackages = [CompatiblePackage("com.reddit.frontpage", ["2024.0.17"])]
```suggestion
    // Constrained to last working version (2024.17.0) until https://github.com/iBotPeaches/Apktool/issues/3534
    // is addressed which is causing crashes during patching.
    // See https://github.com/ReVanced/revanced-patches/issues/3099.
    compatiblePackages = [CompatiblePackage("com.reddit.frontpage", ["2024.17.0"])]
```
Wasn't the last working version `2024.17.0` and not `2024.0.17`?

2024-05-16 12:06 UTC, closed without merging

2024-05-19 11:13 UTC, ericswpark commented
@ascopes why was the head repository deleted? Did another PR supersede this one?

2024-05-19 11:29 UTC, ascopes commented
Ah whoops, I was removing an unused clone for another revanced project and accidentally deleted the wrong one... will reraise with the correct fixes as given above when I get some time!

2024-05-19 11:48 UTC, ascopes commented
Reopened at #3192