fix(YouTube - SponsorBlock/VideoInformation): implement MDX seekTo command to fix skipping while casted to a TV
ReVanced/revanced-patches pull request #3331
Opened 2024-06-11 17:50 UTC by thedroidgeek

Add patch code to support skipping segments while casted to a big screen device, by hooking the MDX director class to intercept object instances in order to be able to call the seekTo method, similar to how it's done in the 'regular' player class.

Fixes https://github.com/ReVanced/revanced-patches/issues/374.

Integrations PR: https://github.com/ReVanced/revanced-integrations/pull/655

2024-06-11 19:32 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +            mdxInitInsertRegister = mdxInitMethod.getInstruction<Instruction35c>(mdxInitInsertIndex - 1).registerC
I kept the static values for easy maintenance - the dynamic resolution code was added after I realized the method was updated and the values had to change between 19.11.43 and 19.16.39.

2024-06-11 19:33 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxPlayerDirectorFingerprint.kt
> +    strings = listOf("MdxDirector setVideoStage ad should be null when videoStage is not an Ad state ")
The code was successfully tested on 18.48.39, 19.04.37, 19.11.43 and 19.16.39 - will test on more versions if needed.

2024-06-11 19:40 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxSeekFingerprint.kt
> +        methodDef.implementation!!.instructions.count() == 3
There's actually a very similar method (seems to have the behavior of seekToRelative) with the exact same signature (arguments and return type), with exactly the same opcodes as the one I hook (except with more instructions on top), which is why I decided to go for instruction count to distinguish between the two.

<details>
  <summary>18.48.39</summary>
  
![image](https://github.com/ReVanced/revanced-patches/assets/11878924/80b63983-1c2d-4be6-a7c7-61a988785763)
![image](https://github.com/ReVanced/revanced-patches/assets/11878924/003f07f7-3602-463e-822a-b2e9e5859949)
  
</details>

2024-06-12 02:11 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +            mdxInitInsertRegister = mdxInitMethod.getInstruction<Instruction35c>(mdxInitInsertIndex - 1).registerC
Done.

2024-06-12 02:11 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxSeekFingerprint.kt
> +        methodDef.implementation!!.instructions.count() == 3
Done.

2024-06-12 02:11 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +            mdxInitInsertIndex = mdxInitMethod.implementation!!.instructions.indexOfFirst {
Done.

2024-06-12 02:11 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +                it.opcode == Opcode.INVOKE_DIRECT && ((it as Instruction35c).reference as MethodReference).name == "<init>"
Done.

2024-06-12 02:12 UTC, thedroidgeek commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxPlayerDirectorFingerprint.kt
> +    strings = listOf("MdxDirector setVideoStage ad should be null when videoStage is not an Ad state ")
All tested.

2024-06-27 20:32 UTC, oSumAtrIX requested changes

2024-06-27 20:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +            val mdxSeekFingerprintResultMethod = MdxSeekFingerprint.also { it.resolve(context, classDef) }.result!!.method
```suggestion
            val mdxSeekFingerprintResultMethod = MdxSeekFingerprint.apply { resolve(context, classDef) }.resultOrThrow().method
```

2024-06-27 20:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +                invoke-virtual {p0, p1, p2, v0}, ${seekMethod.definingClass}->${seekMethod.name}(J$seekSourceEnumType)Z
Should work:

```suggestion
                invoke-virtual {p0, p1, p2, v0}, $seekMethod
```

2024-06-27 20:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +                invoke-virtual {p0, p1, p2, v0}, ${seekMethod.definingClass}->${seekMethod.name}(J$seekSourceEnumType)Z
```suggestion
                invoke-virtual { p0, p1, p2, v0 }, ${seekMethod.definingClass}->${seekMethod.name}(J$seekSourceEnumType)Z
```

2024-06-27 20:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxSeekFingerprint.kt
> +internal object MdxSeekFingerprint : MethodFingerprint(
Quite the loose fingerprint, which could match other methods. Perhaps adding a small opcode pattern should make it a bit more failsafe.

2024-06-27 20:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxPlayerDirectorFingerprint.kt
> +internal object MdxPlayerDirectorFingerprint : MethodFingerprint(
Please name the fingerprint to the method it resolves to. If the name is obfuscated find a suitable name.

2024-07-05 13:44 UTC, thedroidgeek commented
Sorry for the inactivity. @LisoUseInAIKyrios I just tested and everything seems to work properly with these changes.

2024-07-05 13:53 UTC, thedroidgeek reviewed
Review was done by @LisoUseInAIKyrios.

2024-07-10 22:10 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
> +            // find the location of the first invoke-direct call and extract the register storing the 'this' object reference.
```suggestion
            // find the location of the first invoke-direct call and extract the register storing the 'this' object reference
```

2024-07-10 22:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxSeekFingerprint.kt
> +        // regular one, is in the same class, and even has the exact same 3 opcodes pattern
```suggestion
        // regular one, is in the same class, and even has the exact same 3 opcodes pattern.
```

2024-07-10 22:11 UTC, oSumAtrIX approved these changes

2024-07-10 22:12 UTC, merged

2024-07-12 17:26 UTC, oSumAtrIX commented
No