feat: Add universal `Hide Mock Location` patch (#3389)
ReVanced/revanced-patches pull request #3417
Opened 2024-07-06 16:31 UTC by epireyn

2024-07-06 16:35 UTC, oSumAtrIX requested changes

2024-07-06 16:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/location/hide/HideMockLocationPatch.kt
> +    description = "Prevent app from knowing whether the location is mocked",
```suggestion
    description = "Prevent app from knowing whether the location is mocked.",
```

2024-07-06 16:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/location/hide/HideMockLocationPatch.kt
> +    use = true
```suggestion
    use = false
```

2024-07-06 16:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/location/hide/HideMockLocationPatch.kt
> +    name = "Hide Mock Location",
```suggestion
    name = "Hide mock location",
```

2024-07-06 16:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/location/hide/HideMockLocationPatch.kt
> +    description = "Prevent app from knowing whether the location is mocked",
```suggestion
    description = "Spoof the app when mocking the location.",
```

@LisoUseInAIKyrios maybe you have a better description.

2024-07-06 16:52 UTC, epireyn commented
I'm currently removing the dependency on integrations.

2024-07-10 22:18 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/location/hide/HideMockLocationPatch.kt
> +        return Instruction35cInfo(methodCall, invokeInstruction, instructionIndex)
A Pair of invokeInstruction and instructionIndex would suffice here: `BaseTransformInstructionsPatch<Pair<Instruction, Index>()`

2024-07-13 23:41 UTC, oSumAtrIX requested changes
Something here is not right. You don't check for the correct call in filterMap. Please review the patch

2024-07-20 04:00 UTC, oSumAtrIX approved these changes

2024-07-20 04:00 UTC, merged