feat: Add `Disable analytics and telemetry` patches
ReVanced/revanced-patches pull request #3448
Opened 2024-07-17 21:49 UTC by patchink0

Added generic patches to disable multiple analytics and telemetry SDKs: ComScore, AppsFlyer, MoEngage, Segment, Statsig, Facebook SDK, Google Analytics, Firebase Crashlytics, Firebase Logging

Those are all the SDKs included in the SoundCloud app, and the patches were developed and tested on it but should work for any app.

This greatly increases privacy but also performance, more specifically regarding the startup time. SoundCloud initializes and opens up noticeably faster using those patches.

2024-07-17 21:58 UTC, oSumAtrIX requested changes
Looks good on first sight. Once the couple style/refactor issues are addressed it lgtm. I do not know if each patch works here as expected, were they all been tested? The readme of the repository should be changed in this pr as well to include privacy patches as a feature, given this pr introduces pretty much all the common ones.

2024-07-17 22:04 UTC, oSumAtrIX commented
That sounds like a good idea indeed.

2024-07-22 18:52 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/analytics/UniversalPrivacyPatch.kt
> +                Logger.getLogger(this::class.java.name).warning("Applying patch to disable ${it.key.first}")
Yes, info works here.

2024-07-22 19:06 UTC, oSumAtrIX requested changes

2024-07-22 19:06 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/analytics/appsflyer/fingerprints/AppsFlyerInitFingerprint.kt
> +object AppsFlyerInitFingerprint : MethodFingerprint(
Make sure fingerprints are internal

2024-07-23 20:24 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/privacy/UniversalResourcePrivacyPatch.kt
> +    description = "Disables multiple embedded analytics and telemetry SDKs by modifying the app's manifest. Please note this can break some apps.",
>  can a resource patch be included or excluded at runtime?

ReVanced Patcher checks all added patches and their dependencies before patches are ran so it can decode the resources before any patches are executed. Otherwise while patches run, there would be a delay for the first resource patch running.

2024-07-23 21:25 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/privacy/UniversalResourcePrivacyPatch.kt
> +    description = "Disables multiple embedded analytics and telemetry SDKs by modifying the app's manifest. Please note this can break some apps.",
Options are instance members of a patch instance. When a patch is instantiated its dependencies are set. So there is no way for an option to decide weather a patch depends on another. The situation is the following:

Either we have one patch which also employs a resource patch. One patch that does not employ resource patches at all. One resource and one bytecode patch separately or each privacy patch is its own, so multiple bytecode and resource patches.

The initial idea was that we combine all patches so that the patch handles all kinds of analytics patches itself (or via patch options) but if we want to make it work on apps where resource patches fail, we have to move resources patches to a different patch which breaks our initial idea. So either its this or apps which would otherwise just need bytecode patches could potentially fail due to resource patches.

2024-07-31 20:50 UTC, oSumAtrIX commented on README.md
> +* 📡 **Enhance your privacy**: Disable embedded trackers and privacy invasive components
```suggestion
* 📡 **Protect your privacy**: Disable embedded trackers and privacy-invasive components
```

2024-08-16 06:54 UTC, oSumAtrIX commented
I am locally refactoring this PR

2024-08-24 12:43 UTC, oSumAtrIX requested changes
Please test the refactoring changes & my review. Otherwise LGTM

2024-08-24 12:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/privacy/DisableAnalyticsAndTelemetryThroughManifestPatch.kt
> +                .first { it.attributes.getNamedItem(NAME_ATTRIBUTE).nodeValue == nodeName }
I replaced firstOrNull with first here when refactoring. Correct this if it should be firstOrNull. If it should, then the try captch block above isn't necessary which was present before I refactored.

2024-08-24 12:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/privacy/DisableAnalyticsAndTelemetryThroughManifestPatch.kt
> +    private val disableFirebaseTelemetry by option("Firebase telemetry")
I merged the two firebase patches to one.

2024-08-24 12:43 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/all/privacy/DisableAnalyticsAndTelemetryThroughManifestPatch.kt
> +    private val disableGoogleAnalytics by option("Google Analytics")
GAnalytics patch also exists in the bytecode patch, why is it present here as well? Also, can't the firebase & facebook patches be converted to bytecode?

2025-01-30 18:41 UTC, cryeprecision commented
@patchink0 I'd be willing to fork your fork and try to get this merged if you don't have the time for this at the moment.

2025-07-11 15:41 UTC, closed without merging