refactor(YouTube Music): Rename `Hide music video ads` to `Hide multimedia ads` and add patch description
ReVanced/revanced-patches pull request #3494
Opened 2024-08-01 08:51 UTC by ILoveOpenSourceApplications

Closes #3378

2024-08-01 11:23 UTC, oSumAtrIX requested changes
Please dump the API

2024-08-01 11:24 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
Why not just name the patch "Hide video ads"?

2024-08-01 15:02 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
The ad types maybe of video format, but they're being shown when playing different instances. So, the name `Hide video ads` will not be appropriate.

2024-08-01 15:19 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
> The ad types maybe of video format

What do you mean "maybe"?

>  they're being shown when playing different instances

What do you mean instances.

2024-08-01 20:40 UTC, ILoveOpenSourceApplications commented
> Please dump the API

How do I do that?

2024-08-01 20:41 UTC, oSumAtrIX commented
You have to run the dumpAPI task via gradle: `gradlew apiDump`.

2024-08-01 20:41 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
Does YT Music only show video ads across all 3 formats of content?

2024-08-01 21:06 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
Multimedia streaming ads is a suitable term to encompass both audio and display ads within a streaming context.
This term effectively conveys the idea that the ads utilize multiple media formats (audio and visual) to reach the audience on a streaming platform.

2024-08-02 05:38 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
From my short and impatient testing, I'm only coming across ads which are in  video formats when patching without `Hide music video ads`.  May I ask whether this patch also removes the promotion  ads for YT premium between each tracks or not?

2024-08-03 19:54 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideMultimediaAds.kt
> +    name = "Hide multimedia ads",
I'm only seeing video ads and hence renamed the patch accordingly.

2024-08-03 20:12 UTC, oSumAtrIX commented on api/revanced-patches.api
> -public final class app/revanced/patches/music/ad/video/HideMusicVideoAds : app/revanced/patcher/patch/BytecodePatch {
These are breaking changes. If you rename a patch, keep the old patch class and depend on the new renamed patch. Deprecate the old class.

2024-08-03 20:18 UTC, ILoveOpenSourceApplications commented on api/revanced-patches.api
> -public final class app/revanced/patches/music/ad/video/HideMusicVideoAds : app/revanced/patcher/patch/BytecodePatch {
I only did the apiDump, like I was previously instructed. What am I supposed to do now?

2024-08-03 20:29 UTC, ILoveOpenSourceApplications commented on api/revanced-patches.api
> -public final class app/revanced/patches/music/ad/video/HideMusicVideoAds : app/revanced/patcher/patch/BytecodePatch {
Do I have create `HideMusicVideoAds.kt` for this?

2024-08-03 20:38 UTC, ILoveOpenSourceApplications commented on src/main/kotlin/app/revanced/patches/music/ad/video/HideVideoAds.kt
> +object VideoAdsPatch : BytecodePatch(
Do I simply have to rename here?
```suggestion
object MusicVideoAdsPatch : BytecodePatch(
```

2024-08-04 06:23 UTC, ILoveOpenSourceApplications commented
So now everything is looking good?

2024-08-04 08:09 UTC, oSumAtrIX approved these changes

2024-08-04 08:09 UTC, merged