feat(Instagram): Added few patches
ReVanced/revanced-patches pull request #3604
Opened 2024-09-01 12:58 UTC by swakwork

Hi team,

I have added the following patches to [Instagram](https://play.google.com/store/apps/details?id=com.instagram.android)

- Added `Enable developer menu` patch
- Added `Max media quality` patch
- Added `Selectable bio` patch
- Added `Sanitize sharing links` patch
- Added `Open links in external browser` patch

I have tested these with the latest alpha build(348.0.0.0.42) , at the time, and the patches work fine.

This is my first PR to this project, so do let me know if any code correction is needed.

Thanks,

2024-09-01 14:55 UTC, oSumAtrIX commented
The added patches don't add a download patch.

2024-09-01 15:07 UTC, oSumAtrIX requested changes
Looking good. Couple of small issues that need to be addressed before merging though. I have commented in some places but other applicable places should be considered as well.

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/developerMenu/EnableDeveloperMenuPatch.kt
> +        val ref = (method.getInstruction<BuilderInstruction35c>(loc).reference as DexBackedMethodReference)
Do not abbreviate. By style and convention we use full names. loc -> index, ref -> methodReference.
Also be descriptive if possible. Instead of just "index" you can say "isDeveloperModeEnabledIndex" (if that's actually the case".

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/developerMenu/EnableDeveloperMenuPatch.kt
> +        val inject_method = context.findClass(className)!!.mutableClass.methods.first { it.name == methodName }
Use thisCasing for variables.

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/developerMenu/fingerprints/EnableDeveloperMenuFingerprint.kt
> +internal object EnableDeveloperMenuFingerprint:MethodFingerprint(
Fingerprints should be called after the method they match to. For this, eg.: ShouldAddPrefTTLFingerprint

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/misc/links/openInExternalBrowser/OpenLinksInExternalBrowser.kt
> +        //create a field of type String to hold url
Add comments that explain why you do things that arent apparent. It is unclear why you add a new field.

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/misc/links/openInExternalBrowser/fingerprints/OpenLinksInExternalBrowserFingerprint.kt
> +
Format the code. Use "Ktlint" (or the plugin for IDEA)

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/misc/links/sanitizeSharingLinks/SanitizeSharingLinksPatch.kt
> +    private fun addCode(method: MutableMethod){
Inline this into addFunction as a local function

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/misc/maxQuality/MaxMediaQualityPatch.kt
> +    description = "Makes media quality to max",
Which kind of media? The one in the feed? When is the media quality reduced?

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/misc/maxQuality/MaxMediaQualityPatch.kt
> +        //set bitrate to 10000000
Is this an arbitrary number?

2024-09-01 15:07 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/misc/maxQuality/MaxMediaQualityPatch.kt
> +    override fun execute(context: BytecodeContext) {
Please explain your strategy or what is going on in this patch with comments

2024-09-01 15:09 UTC, oSumAtrIX commented
PRs are squashed to one commit. Either separate each patch to its own PR, or squash them locally into commits called "feat(Instagram): Added `Patch name` patch" so we can merge as a rebase.

2024-09-01 16:09 UTC, oSumAtrIX commented
No it just changes the media quality

2024-09-01 17:28 UTC, swakwork commented
> PRs are squashed to one commit. Either separate each patch to its own PR, or squash them locally into commits called "feat(Instagram): Added `Patch name` patch" so we can merge as a rebase.

oh alright, I wasnt aware of it. Lemme correct the code base with the above mentioned corrections and create PRs individually. We can probably close this one (then).

2024-09-01 17:30 UTC, oSumAtrIX commented
Working in a single pr is easier (also to review). We can decide that once all codebase issues are resolved 👍

2024-09-02 07:46 UTC, swakwork commented
Hi,

Updated the codebase with the mentioned comments. Let me know if it looks good now.
Also thanks for suggesting "Ktlint".

2024-09-02 08:11 UTC, oSumAtrIX requested changes

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/links/openInExternalBrowser/OpenLinksInExternalBrowser.kt
> +                val const4 = browserCallMethod.getInstructions().first { it.opcode == Opcode.CONST_4 }
Describe what this variable is or for what it is used for. We know its const_4 because you look for it in first { } but we don't know its purpose in the patch.

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/links/sanitizeSharingLinks/SanitizeSharingLinksPatch.kt
> +        fun addFunction(method: MutableMethod) {
In java there only methods not functions.

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/links/sanitizeSharingLinks/SanitizeSharingLinksPatch.kt
> +            val register = method.getInstruction<OneRegisterInstruction>(index).registerA
What is "link register", please be descriptive, make it easy for readers of open source code to understand it.

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/links/sanitizeSharingLinks/SanitizeSharingLinksPatch.kt
> +            move-result-object v$register
Always indent one more than """ :)

```suggestion
		            invoke-static{v$register}, $FUNC_CALL
		            move-result-object v$register
```

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/links/sanitizeSharingLinks/SanitizeSharingLinksPatch.kt
> +        addFunction(LiveShareUrlFingerprint.resultOrThrow().mutableMethod)
You could ask for the fingerprint and get rid of duplication by calling resultOrThrow().mutableMethod inside the function.

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        // This section of code removes that restriction and sets the resolution to 2048x2048 (max possible).
Why would you ever want to do that? If your device cant display more than the maximum, whats the usecase of this patch?

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        // Media size.
Try to use full sentences if possible.

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        // Reels
Make sure you are consistent. Stories above ends with punctuation, this doesn't.

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/selectableBio/SelectableBioPatch.kt
> +    description = "Make the user's bio selectable",
Descriptions end with . as a convention in this project

2024-09-02 08:11 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/selectableBio/SelectableBioPatch.kt
> +    use = false,
Any reason why we dont want this patch by default?

2024-09-02 08:12 UTC, oSumAtrIX commented
The review will be iterative, addressing big issues, once solved, smaller issues and so on, until everything looks right. Hope it doesn't cause too much trouble.

2024-09-02 11:45 UTC, swakwork commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        // This section of code removes that restriction and sets the resolution to 2048x2048 (max possible).
For better viewing quality

2024-09-02 11:46 UTC, swakwork commented on src/main/kotlin/app/revanced/patches/instagram/patches/selectableBio/SelectableBioPatch.kt
> +    use = false,
I thought its was mandate to set patches to "off" by default. Removed them in the latest push

2024-09-02 18:59 UTC, swakwork commented
Updated the `Sanitize sharing links` patch to sanitize profile and highlights links.
Do let me know if any more correction is required and also if  `Max media quality` patch is not a worth the time, so that I can remove it

2024-09-03 04:45 UTC, kazimmt commented
> Does possible to download media ...

@crimera was working on download patch. But he didn't complete the job yet.
https://github.com/crimera/piko/pull/222

2024-09-03 07:31 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/selectableBio/SelectableBioPatch.kt
> +    use = false,
Only patches you think that most users wouldn't want or need should be set to false

2024-09-03 07:31 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        // This section of code removes that restriction and sets the resolution to 2048x2048 (max possible).
How is it better when Instagram uses the highest of your device?

2024-09-06 08:28 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        // This section of code removes that restriction and sets the resolution to 2048x2048 (max possible).
Please add that to the patch description so the user can understand that they might want the patch for that purpose

2024-09-06 08:29 UTC, oSumAtrIX commented
@swakwork You can mark reviews as resolved to hide them.

2024-09-06 17:14 UTC, swakwork commented
> @swakwork You can mark reviews as resolved to hide them.

yup, done 👍

2024-09-06 17:19 UTC, kazimmt commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        "Instagram ,sometimes, compresses the media resolution with respect to device dimensions causing quality loss. " +
Instagram occasionally compresses media resolution based on device dimensions, leading to a loss in quality.

Or just remove those unwanted comma's

2024-09-06 17:20 UTC, swakwork commented on src/main/kotlin/app/revanced/patches/instagram/patches/maxQuality/MaxMediaQualityPatch.kt
> +        "Instagram ,sometimes, compresses the media resolution with respect to device dimensions causing quality loss. " +
thanks

2024-09-14 14:34 UTC, swakwork commented
Hi team,  is there any other cleanups required from my end or the changes looks good ?

2024-09-17 14:31 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/bio/SelectableBioPatch.kt
> +    setOf(SelectableBioFingerprint),
Please name fingerprints to the method they match to. If this one for example matches to the constructor, call it "ConstructBioViewFingerprint"

2024-09-17 14:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/browser/OpenLinksInExternalBrowser.kt
> +            it.mutableClass.methods.last { it.returnType == "V" && it.parameters.size == 0 }.apply {
This is not a safe approach. Please fingerprint the method and get it through that.

2024-09-17 14:32 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/browser/fingerprints/OpenLinksInExternalBrowserFingerprint.kt
> +internal object OpenLinksInExternalBrowserFingerprint : MethodFingerprint(
Name the fingerprint like explained above.

2024-09-17 14:33 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/tracking/SanitizeSharingLinksPatch.kt
> +        HighlightsShareUrlFingerprint,
These fingerprints need to be named according to the method they match too

2024-09-17 14:33 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/tracking/SanitizeSharingLinksPatch.kt
> +            val index = getInstructions().first { it.opcode == Opcode.IPUT_OBJECT }.location.index - 2
Please comment what this index does in the code

2024-09-17 14:33 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/tracking/SanitizeSharingLinksPatch.kt
> +        }
Why aren't you using a fingerprint for this?

2024-09-17 14:34 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/misc/quality/MaxMediaQualityPatch.kt
> +        val maxBitRate = "0x989680" // Decimal value = 10000000. Maximum bit rate possible (found in code).
Iirc you can use decimals just fine in smali, no need to convert to hex

2024-09-17 14:34 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/misc/quality/MaxMediaQualityPatch.kt
> +            it.mutableMethod.apply {
If you do not use the result, simply do DisplayMetricsFingerprint.resultOrThrow().mutableMethod.

2024-09-17 14:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/misc/quality/MaxMediaQualityPatch.kt
> +                    methods.first { it.returnType == "Lcom/instagram/model/mediasize/ExtendedImageUrl;" }
Why not fingerprint this method in the first place?

2024-09-17 14:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/instagram/patches/misc/quality/MaxMediaQualityPatch.kt
> +                val ifLezIndex = getInstructions().first { it.opcode == Opcode.IF_LEZ }.location.index
Use opcode patterns in fingerprint to get the index to instructions.

2024-10-09 15:21 UTC, swakwork commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/tracking/SanitizeSharingLinksPatch.kt
> +        }
Sorry my bad. I thought the lesser the fingerprint the better. Looks like I was wrong 😅

2024-10-09 16:31 UTC, swakwork commented on src/main/kotlin/app/revanced/patches/instagram/patches/interaction/links/browser/OpenLinksInExternalBrowser.kt
> +            it.mutableClass.methods.last { it.returnType == "V" && it.parameters.size == 0 }.apply {
Basically that method originally has 4 lines, 2 const/4, 1 invoke and return-void. Moreover both the "get url" method and the method where the fragment is built is present in the same call. So I thought its easier to find the class and then find the methods accordingly

2025-01-28 14:03 UTC, oSumAtrIX commented
Migrating is fairly simple, though you can continue the PR on the current base and we can take over with the migration once done.

2025-03-27 01:13 UTC, Aunali321 commented
@swakwork Hi, still interested in working on this PR?

2025-03-27 01:17 UTC, Aunali321 commented
I implemented most of the patches here: https://github.com/Aunali321/ReVancedExperiments/tree/main/patches/src/main/kotlin/li/auna/patches/instagram

2025-03-27 01:18 UTC, oSumAtrIX commented
https://github.com/Aunali321/ReVancedExperiments/tree/main/patches/src/main/kotlin/li/auna/patches/instagram seems to have implemented the patches. Closing this for now.

2025-03-27 01:18 UTC, closed without merging

2025-03-27 05:44 UTC, CrazyWolf13 commented
@Aunali321 Thanks a lot!

Any ideas what about the mentioned download function?

[crimera/piko#222](https://github.com/crimera/piko/pull/222)

Also will these patches from your ExperimentPatches end up on the main Revanced Patches Repo or is this something different?

2025-03-27 06:00 UTC, Aunali321 commented
No plans for download patch yet. 
And use can use my bundle by changing custom source in manager or cli. No plans to upstream yet