feat(Google Photos): Show hidden 'Back up while charging' toggle
ReVanced/revanced-patches pull request #3678
Opened 2024-09-22 15:41 UTC by xob0t

This toggle is hidden by default, when enabled, backups run only when the device is charging.

<details>
  <summary>screenshot</summary>
 
![image](https://github.com/user-attachments/assets/44a094d5-18f5-4f73-858b-cb963766c9d0)
  
</details>

2024-09-22 17:02 UTC, oSumAtrIX commented
Why is the toggle hidden?

2024-09-22 17:41 UTC, xob0t commented
@oSumAtrIX 
It was an option that Google removed at some point. Just because. Google being Google.

https://thenextweb.com/news/google-photos-backup-charging

But if the user had enabled it before, the flag `backup_prefs_had_backup_only_when_charging_enabled` was set to true to keep it available for you. This path does the same.

2024-09-22 23:47 UTC, oSumAtrIX requested changes

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/ShowBackUpWhileChargingPatch.kt
> +        // patches 'backup_prefs_had_backup_only_when_charging_enabled' to always be true
Follow this comment style:

```suggestion
        // Patches 'backup_prefs_had_backup_only_when_charging_enabled' to always be true.
```

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/ShowBackUpWhileChargingPatch.kt
> +            val chargingPrefStringIndex = it.scanResult.stringsScanResult!!.matches.first().index
There's trailing whitespace. Please format the code

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/ShowBackUpWhileChargingPatch.kt
> +                addInstruction(chargingPrefStringIndex + 3, "const/4 v$resultRegister, 0x1")
Please add a comment for this offset such as if it is before the return instruction

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/fingerprints/BackupPreferencesFingerprint.kt
> +                ),
Format the code (Use ktlint extension for intellij idea)

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/ShowBackUpWhileChargingPatch.kt
> +object BackupPreferencesFingerprint : BytecodePatch(
This name is not correct.

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/ShowBackUpWhileChargingPatch.kt
> +    description = "This toggle is hidden by default, when enabled, backups run only when the device is charging",
```suggestion
    description = "Restores a hidden toggle to only run backups when the device is charging.",
```

2024-09-22 23:47 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/googlephotos/preferences/ShowBackUpWhileChargingPatch.kt
> +    name = "Show hidden 'Back up while charging' toggle",
```suggestion
    name = "Restore hidden 'Back up while charging' toggle",
```

2024-09-23 13:40 UTC, oSumAtrIX commented
Uploading is just transferring files over network. Unless there's some weird compression going in client side this shouldn't even begin to be a problem

2024-09-29 00:22 UTC, oSumAtrIX approved these changes

2024-09-29 00:22 UTC, merged