feat: disable shorts player at app startup
revanced/revanced-patches pull request #562
Opened 2022-09-20 23:30 UTC by OxrxL

2022-09-20 23:44 UTC, oSumAtrIX requested changes
This patch would need a bit of cleaning on the implementation side, after that it can be merged.

2022-09-20 23:44 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/patch/StartupShortsResetPatch.kt
> +@Description("Disable shorts player invoke after app execution.")
```suggestion
@Description("Disable playing YouTube Shorts when launching YouTube.")
```

2022-09-20 23:44 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/patch/StartupShortsResetPatch.kt
> +class StartupShortsResetPatch : BytecodePatch(
Please name this class `DisableShortsOnStartupPatch` to match with the patch name.

2022-09-24 23:26 UTC, OxrxL commented
Refactored as well :)

2022-09-27 04:57 UTC, oSumAtrIX requested changes

2022-09-27 04:57 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/patch/DisableShortsOnStartupPatch.kt
> +            const/4 v$moveResultRegister, 0x1
It shouldn't be necessary for all this code for 3 registers. Instead use an opcode pattern as an anchor in the instructions to find the registers in a better way.

2022-09-28 11:35 UTC, oSumAtrIX requested changes

2022-09-28 11:35 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/patch/DisableShortsOnStartupPatch.kt
> +        val parentResult = ActionOpenShortsFingerprint.result!!
You should resolve the fingerprint on another fingerprints result, not itself.

2022-09-29 16:26 UTC, closed without merging