feat: hide settings email address
revanced/revanced-patches pull request #578
Opened 2022-09-21 20:23 UTC by OxrxL

2022-09-21 20:25 UTC, OxrxL commented
@oSumAtrIX patch code is weird like on the previous PR, but it's just a placeholder until will not be rewritten.

2022-09-21 20:55 UTC, oSumAtrIX requested changes
Overall a bit messy, would require some refactoring before merging.

2022-09-21 20:55 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/emailaddressvisibility/patch/EmailAddressVisibilityPatch.kt
> +@DependsOn([IntegrationsPatch::class, SettingsPatch::class])
```suggestion
@DependsOn([IntegrationsPatch::class, SettingsPatch::class, ResourceIdMappingProviderResourcePatch::class])
```

2022-09-24 22:57 UTC, OxrxL commented
@oSumAtrIX Refactored ;)

2022-09-27 04:45 UTC, oSumAtrIX requested changes

2022-09-27 04:45 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patches/youtube/layout/personalinformation/patch/HideEmailAddressPatch.kt
> +            const/16 v$setVisibilityRegister, 0x8
All of this should be refactored. For two registers a proper pattern should be used in the fingerprint.

2022-09-28 11:28 UTC, merged