feat: `sponsorblock` patch
revanced/revanced-patches pull request #76
Opened 2022-06-29 18:51 UTC by oSumAtrIX

2022-06-29 20:03 UTC, xemulat commented
Sponsorblock Integration? I must update my packages...

2022-06-30 10:29 UTC, TheJeterLP requested changes

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            2, "invoke-static {p1, p2}, Lpl/jakubweg/PlayerController;->setCurrentVideoTime(J)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            0, "invoke-static {p1, p2}, Lpl/jakubweg/PlayerController;->setCurrentVideoTimeHighPrecision(J)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                 invoke-static {v$videoIdRegister}, Lpl/jakubweg/PlayerController;->setCurrentVideoId(Ljava/lang/String;)V
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                 invoke-static {}, Lfi/razerman/youtube/XGlobals;->NewVideoStarted()V
app/revanced/integrations/videoplayer/videosettings/VideoSpeed

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                 invoke-static {v$videoIdRegister}, Lfi/vanced/libraries/youtube/player/VideoInformation;->setCurrentVideoId(Ljava/lang/String;)V
app/revanced/integrations/sponsorblock/player/VideoInformation

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            1, "invoke-static {v0}, Lpl/jakubweg/PlayerController;->setSponsorBarRect(Ljava/lang/Object;)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                "invoke-static {v${invokeInstruction.registerC}}, Lpl/jakubweg/PlayerController;->setSponsorBarThickness(I)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {v$rectangleLeftRegister}, Lpl/jakubweg/PlayerController;->setSponsorBarAbsoluteRight(Landroid/graphics/Rect;)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {v$rectangleRightRegister}, Lpl/jakubweg/PlayerController;->setSponsorBarAbsoluteRight(Landroid/graphics/Rect;)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {v$canvasInstance, v$centerY}, Lpl/jakubweg/PlayerController;->drawSponsorTimeBars(Landroid/graphics/Canvas;F)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {v$videoLengthRegister}, Lpl/jakubweg/PlayerController;->setVideoLength(J)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                                invoke-static {v$inflatedViewRegister}, Lpl/jakubweg/ShieldButton;->initialize(Ljava/lang/Object;)V
app/revanced/integrations/sponsorblock/ShieldButton

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                                invoke-static {v$inflatedViewRegister}, Lpl/jakubweg/VotingButton;->initialize(Ljava/lang/Object;)V
app/revanced/integrations/sponsorblock/VotingButton

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                                invoke-static {p1}, Lpl/jakubweg/VotingButton;->changeVisibilityNegatedImmediate(Z)V
app/revanced/integrations/sponsorblock/VotingButton

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                                invoke-static {p1}, Lpl/jakubweg/ShieldButton;->changeVisibilityNegatedImmediate(Z)V
app/revanced/integrations/sponsorblock/ShieldButton

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                invoke-static {p1}, Lpl/jakubweg/ShieldButton;->changeVisibility(Z)V
app/revanced/integrations/sponsorblock/ShieldButton

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                invoke-static {p1}, Lpl/jakubweg/VotingButton;->changeVisibility(Z)V
app/revanced/integrations/sponsorblock/VotingButton

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {p$instanceRegister}, Lpl/jakubweg/PlayerController;->addSkipSponsorView15(Landroid/view/View;)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +                    invoke-static {p$targetRegister}, Lpl/jakubweg/SponsorBlockUtils;->appendTimeWithoutSegments(Ljava/lang/String;)Ljava/lang/String;
app/revanced/integrations/sponsorblock/SponsorBlockUtils

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {v$initInstanceRegister}, Lpl/jakubweg/PlayerController;->onCreate(Ljava/lang/Object;)V"
app/revanced/integrations/sponsorblock/PlayerController

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {v$watchWhileActiveInstance}, Lfi/vanced/libraries/youtube/dialog/Dialogs;->showDialogsAtStartup(Landroid/app/Activity;)V" // TODO: separate ryd and sb dialogs
Call app/revanced/integrations/ryd/dialog/Dialogs and app/revanced/integrations/sponsorblock/dialog/Dialogs

2022-06-30 10:29 UTC, TheJeterLP commented on src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/patch/SponsorBlockPatch.kt
> +            "invoke-static {p0}, Lfi/vanced/libraries/youtube/sponsors/player/ui/SponsorBlockView;->initialize(Ljava/lang/Object;)V"
app/revanced/integrations/sponsorblock/player/ui/SponsorBlockView

2022-07-02 16:08 UTC, closed without merging